language: python
python:
- "2.7"

env:
- PYTHONPATH=src

script: 
- cd tests
- python -m unittest aboutTests csnAPITests csnContextTests csnGUIHandlerTests csnGUIOptionsTests csnUtilityTests versionTests
