language: python
python:
- "2.7"

env:
- PYTHONPATH=../src

before_script:
- wget -P tmp http://www.cmake.org/files/v2.8/cmake-2.8.10.tar.gz
- tar xz -C tmp -f tmp/cmake-2.8.10.tar.gz
- cd tests

script: 
- python -m AllTests
