language: python
python:
- "2.7"

env:
- PYTHONPATH=src

script: 
- python -m unittest tests.aboutTests tests.csnAPITests tests.csnContextTests tests.csnGUIHandlerTests tests.csnGUIOptionsTests tests.csnUtilityTests tests.versionTests
