#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-
# generated by wxGlade 0.6.3 on Wed Oct 15 18:55:59 2008

import wx

# begin wxGlade: extracode
# end wxGlade



class Dialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Dialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.checkbox_1 = wx.CheckBox(self, -1, "checkbox_1")
        self.btnClose = wx.Button(self, -1, "Close")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnClose, self.btnClose)
        # end wxGlade
        
        self.Bind(wx.EVT_CLOSE, self.OnClose, self)
        
    def __set_properties(self):
        # begin wxGlade: Dialog.__set_properties
        self.SetTitle("Select project types to be included")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Dialog.__do_layout
        sizerItems = wx.BoxSizer(wx.VERTICAL)
        sizerItems.Add(self.checkbox_1, 0, 0, 0)
        sizerItems.Add(self.btnClose, 1, wx.ALL|wx.EXPAND, 5)
        self.SetSizer(sizerItems)
        sizerItems.Fit(self)
        self.Layout()
        # end wxGlade
        self.sizerItems = sizerItems
        
    def ShowItems(self, items, filter):
        self.sizerItems.Clear()
        self.checkbox_1.Hide()
        self.checkBoxes = dict()
        self.filter = filter
        for item in sorted(items):
            self.checkBoxes[item] = wx.CheckBox(self, -1, item)
            self.checkBoxes[item].SetValue( not item in filter )
            self.sizerItems.Add(self.checkBoxes[item], 0, 0, 0)
        self.sizerItems.Add(self.btnClose, 1, wx.ALL|wx.EXPAND, 5)
        self.sizerItems.Fit(self)
        self.Layout()
        return self.ShowModal()
        
    def OnClose(self, event): # wxGlade: Dialog.<event_handler>
        while len(self.filter):
            self.filter.pop()
        for item in self.checkBoxes.keys():
            if not self.checkBoxes[item].GetValue():
                self.filter.append(item)
        self.MakeModal(0)
        self.Destroy()

# end of class Dialog


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    dialog = Dialog(None, -1, "")
    app.SetTopWindow(dialog)
    dialog.Show()
    app.MainLoop()
