/** 
DO NOT EDIT, CHANGES WILL BE LOST.
This file is automatically generated. 
It is used to set the value of the export macro. This macro determines if functions are exported (in case of building
the dll), imported (in case of using the dll) or neither (in case of building and using a static lib).
*/

#ifndef ${PROJECTNAME}WIN32Header_h
#define ${PROJECTNAME}WIN32Header_h

#define ${PROJECTNAME_UPPERCASE}_EXPORT // ${PROJECTNAME} is a static lib, so don't import or export anything

#endif
