/** 
DO NOT EDIT, CHANGES WILL BE LOST.
This file is automatically generated. 
It is used to set the value of the export macro. This macro determines if functions are exported (in case of building
the dll), imported (in case of using the dll) or neither (in case of building and using a static lib).
*/

#ifndef ${PROJECTNAME}WIN32Header_h
#define ${PROJECTNAME}WIN32Header_h

// Add Windows variants

#if defined(__CYGWIN__)
#ifndef WIN32
#define WIN32 1
#endif
#ifndef _WIN32
#define _WIN32 1
#endif
#endif

/** Disable some common warnings in MS VC++ */
#if defined(_MSC_VER)
// 'identifier' : identifier was truncated to 'number' characters in the debug information
#pragma warning ( disable : 4786 ) 
// Disables warning C4675: resolved overload was found by argument-dependent lookup
#pragma warning ( disable : 4675 ) 
#endif

#undef ${PROJECTNAME_UPPERCASE}_EXPORT
#if (defined(_WIN32) || defined(WIN32))
#	ifdef ${PROJECTNAME}_EXPORTS
#		define ${PROJECTNAME_UPPERCASE}_EXPORT __declspec(dllexport)
#	else
#		define ${PROJECTNAME_UPPERCASE}_EXPORT __declspec(dllimport)
#	endif
#else
#	define ${PROJECTNAME_UPPERCASE}_EXPORT // unix needs nothing
#endif

#endif
