#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-
# generated by wxGlade 0.5 on Sat Sep 15 14:23:13 2007 from D:\Users\Maarten\Projects\Gimias\Prog\GIMIAS.cmake\GBuild\csnGUI.wxg

from wx import xrc
import csnGUIHandler
import csnGUIOptions
import csnContext
from csnListener import ChangeListener, ProgressListener, ProgressEvent
import csnBuild
import csnUtility
import os.path
import sys
import shutil
import string
import time
import subprocess
import xrcbinder
from optparse import OptionParser
from about import About
import wx.grid

# Only there to allow its inclusion when generating executables.
import csnCilab #@UnusedImport
import webbrowser
import logging
import copy
import re

class PathPickerCtrl(wx.Control):
    def __init__(self, parent, id=-1, pos=(-1,-1), size=(-1,-1), style=0, validator=wx.DefaultValidator, name="PathPicker", evtHandler=None, folderName="Folder"):
        wx.Control.__init__(self, parent, id=id, pos=pos, size=size, style=style|wx.BORDER_NONE, validator=validator, name=name)
        
        self.evtHandler = evtHandler
        
        self.oldValue = None
        self.grid = None
        self.row = None
        self.col = None
        self.handlerConnected = False
        self.folderName = folderName
        self.dontLeaveEditMode = False
        
        self.panel = wx.Panel(self, style = wx.BORDER_NONE)
        self.text = wx.TextCtrl(self.panel, style = wx.TE_PROCESS_TAB | wx.TE_PROCESS_ENTER)
        self.button = wx.Button(self.panel, label='...')
        self.button.SetMinSize((30, -1))
        self.panel.Bind(wx.EVT_BUTTON, self.OnButtonClick)
        
        self.sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer.Add(self.text, flag=wx.EXPAND, proportion=1)
        self.sizer.Add(self.button, flag=wx.EXPAND, proportion=0)
        self.panel.SetSizer(self.sizer)
        
        self.windows = [self, self.panel, self.text, self.button]
        for window in self.windows:
            window.Bind(wx.EVT_KILL_FOCUS, self.OnSomeoneLostFocus)
        self.Bind(wx.EVT_SET_FOCUS, self.OnGotFocus)
        self.text.Bind(wx.EVT_KEY_DOWN, self.OnKeyDown)
        self.button.Bind(wx.EVT_KEY_DOWN, self.OnKeyDown)
        
    def OnButtonClick(self, event):
        self.dontLeaveEditMode = True
        oldValue = self.text.GetValue()
        dlg = wx.DirDialog(None, "Select %s" % self.folderName, oldValue, wx.DD_DIR_MUST_EXIST)
        if dlg.ShowModal() == wx.ID_OK:
            self.text.SetValue(dlg.GetPath().replace("\\", "/"))
            self.MoveGridCursor(0, 0)
        self.dontLeaveEditMode = False
        
    def OnKeyDown(self, event):
        if event.GetKeyCode()==wx.WXK_TAB:
            self.MoveGridCursor(0, 1)
            event.Skip(False)
        elif event.GetKeyCode()==wx.WXK_RETURN:
            self.MoveGridCursor(1, 0)
            event.Skip(False)
        elif event.GetKeyCode()==wx.WXK_ESCAPE:
            self.SetValue(self.oldValue)
            self.MoveGridCursor(0, 0)
            self.grid.SetFocus()
            event.Skip(False)
        else:
            event.Skip(True)
    
    def MoveGridCursor(self, diffRow, diffCol):
        newRow = self.row + diffRow
        self.grid.SetFocus()
        if newRow >= self.grid.GetTable().GetNumberRows():
            newRow = self.row
        newCol = self.col + diffCol
        if newCol >= self.grid.GetTable().GetNumberCols():
            newCol = self.col
        self.grid.SetGridCursor(newRow, newCol)
        self.grid.ClearSelection()
        self.grid.SelectRow(newRow)
    
    def OnGotFocus(self, event):
        self.text.SetFocus()
        event.Skip()
        
    def OnSomeoneLostFocus(self, event):
        if not self.handlerConnected:
            if not (self.FindFocus() in self.windows) and not self.dontLeaveEditMode:
                self.evtHandler.ProcessEvent(event)
    
    def SetDimensions(self, x, y, width, height, sizeFlags):
        wx.Control.SetDimensions(self, x, y, width, height, sizeFlags)
        self.panel.SetDimensions(x=0, y=0, width=width, height=height, sizeFlags=sizeFlags)
    
    def SetInitialValue(self, value):
        self.oldValue = value
        self.SetValue(value)
        
    def SetValue(self, value):
        self.text.SetValue(value)
        self.text.SetInsertionPointEnd()
        
    def GetValue(self):
        return self.text.GetValue()
    
    def SetGrid(self, row, col, grid):
        self.row = row
        self.col = col
        self.grid = grid
    
class PathPickerEditor(wx.grid.PyGridCellEditor):
    def __init__(self, folderName = "Folder"):
        wx.grid.PyGridCellEditor.__init__(self)
        self.handlerConnected = False
        self.folderName = folderName
    
    def ConnectHandler(self):
        if not self.handlerConnected:
            self._picker.PushEventHandler(self.evtHandler)
            self.handlerConnected = True
            self._picker.handlerConnected = True

    def DisconnectHandler(self):
        if self.handlerConnected:
            self._picker.PopEventHandler()
            self.handlerConnected = False
            self._picker.handlerConnected = False
    
    def Create(self, parent, id, evtHandler):
        self._picker = PathPickerCtrl(parent=parent, id=id, evtHandler=evtHandler, folderName=self.folderName)
        self.value = ""
        self.SetControl(self._picker)
        self.evtHandler = evtHandler
        self.ConnectHandler()
 
    def SetSize(self, rect):
        self._picker.SetDimensions(rect.x, rect.y, rect.width, rect.height, wx.SIZE_ALLOW_MINUS_ONE)
 
    def Show(self, show, attr):
        super(PathPickerEditor, self).Show(show, attr)
 
    def PaintBackground(self, rect, attr):
        pass
 
    def BeginEdit(self, row, col, grid):
        self.DisconnectHandler()
        self.value = str(grid.GetTable().GetValue(row, col)).strip()
        self._picker.SetInitialValue(self.value)
        self._picker.SetGrid(row, col, grid)
        self._picker.SetFocus()
 
    def EndEdit(self, row, col, grid):
        changed = False
        value = self._picker.GetValue()
        if value != self.value:
            changed = True
            grid.SetCellValue(row, col, value) # update the table
            self.value = value
        self.ConnectHandler()
        return changed
 
    def Reset(self):
        pass
 
    def IsAcceptedKey(self, evt):
        return (not (evt.ControlDown() or evt.AltDown()) and
                evt.GetKeyCode() != wx.WXK_SHIFT)
 
    def StartingKey(self, evt):
        key = evt.GetKeyCode()
        if key in [ wx.WXK_NUMPAD0, wx.WXK_NUMPAD1, wx.WXK_NUMPAD2, wx.WXK_NUMPAD3,
                    wx.WXK_NUMPAD4, wx.WXK_NUMPAD5, wx.WXK_NUMPAD6, wx.WXK_NUMPAD7,
                    wx.WXK_NUMPAD8, wx.WXK_NUMPAD9
                    ]:
 
            ch = chr(ord('0') + key - wx.WXK_NUMPAD0)
            self._picker.SetValue(ch)
        elif key < 256 and key >= 0 and chr(key) in string.printable:
            ch = chr(key)
            self._picker.SetValue(ch)
        elif key in [wx.WXK_DELETE, wx.WXK_BACK]:
            self._picker.SetValue("")
        
        evt.Skip()
 
    def StartingClick(self):
        pass
 
    def Clone(self):
        return PathPickerEditor(folderName = self.folderName)

class SelectFolderCallback:
    """ 
    Lets the user choose a path, then calls 'callback' to set the path value in the domain layer, 
    and calls app.UpdateGUI.
    """
    def __init__(self, message, callbackGet, callbackSet, app):
        self.message = message
        self.callbackGet = callbackGet
        self.callbackSet = callbackSet
        self.app = app
        
    def __call__(self, event = None):
        oldValue = self.callbackGet()
        
        dlg = wx.DirDialog(None, self.message, oldValue, wx.DD_DIR_MUST_EXIST)
        
        if dlg.ShowModal() == wx.ID_OK:
            self.callbackSet(dlg.GetPath().replace("\\", "/"))
        self.app.UpdateGUI()
        
class CSnakeGUIApp(wx.App):
    def OnInit(self):
        # logging init
        self.__logger = logging.getLogger("CSnake")

        self.destroyed = False
        self.listOfPossibleTargets = []
        self.projectCheckBoxes = dict()
        
        self.context = None
        self.originalContextData = None
        self.contextFilename = None
        self.contextModified = False
        self.changeListener = ChangeListener(self)
        self.progressListener = ProgressListener(self)
        self.__cancelAction = False
       
        self.projectNeedUpdate = False
        
        wx.InitAllImageHandlers()
        xrcFile = csnUtility.GetRootOfCSnake() + "/resources/csnGUI.xrc"
        self.res = xrc.XmlResource(xrcFile)
        
        self.csnakeFolder = os.path.expanduser("~/.csnake")
        self.thisFolder = None
            
        self.InitFrame()
        self.InitMenu()
        self.InitOtherGUIStuff()
        self.Initialize()
        self.SetTopWindow(self.frame)
        return 1

    def InitFrame(self):
        self.frame = self.res.LoadFrame(None, "frmCSnakeGUI")
        self.binder = xrcbinder.Binder(self, self.frame)
        
        self.textLog = xrc.XRCCTRL(self.frame, "textLog")
        self.binder.AddTextControl("txtBuildFolder", buddyClass = "context", buddyField = "_ContextData__buildFolder", isFilename = True)
        self.binder.AddTextControl("txtInstallFolder", buddyClass = "context", buddyField = "_ContextData__installFolder", isFilename = True)
        self.binder.AddTextControl("txtKDevelopProjectFolder", buddyClass = "context", buddyField = "_ContextData__kdevelopProjectFolder", isFilename = True)
        self.binder.AddTextControl("txtCMakePath", buddyClass = "context", buddyField = "_ContextData__cmakePath", isFilename = True)
        self.binder.AddTextControl("txtPythonPath", buddyClass = "context", buddyField = "_ContextData__pythonPath", isFilename = True)
        self.binder.AddTextControl("txtVisualStudioPath", buddyClass = "context", buddyField = "_ContextData__idePath", isFilename = True)
        # not the good buddyField since combo has "instance - csn file" format...
        self.binder.AddComboBox("cmbCSnakeFile", valueListFunctor = self.GetCSnakeFileComboBoxItems, buddyClass = "context", buddyField = "_ContextData__csnakeFile", isFilename = True)
        self.binder.AddComboBox("cmbInstance", valueListFunctor = self.GetInstanceComboBoxItems, buddyClass = "context", buddyField = "_ContextData__instance")
        self.binder.AddDropDownList("cmbCompiler", valueListFunctor = self.GetCompilerComboBoxItems, buddyClass = "context", buddyField = "_ContextData__compilername")
        self.binder.AddDropDownList("cmbBuildType", valueListFunctor = self.GetBuildTypeComboBoxItems, buddyClass = "context", buddyField = "_ContextData__configurationName")
        self.binder.AddListBox("lbxRootFolders", buddyClass = "context", buddyField = "_ContextData__rootFolders", isFilename = True)
        self.binder.AddCheckBox("chkAskToLaunchVisualStudio", buddyClass = "options", buddyField = "_Options__askToLaunchIDE")
        
        self.binder.AddGrid("gridThirdPartySrcAndBuildFolders", buddyClass = "context", buddyField = "_ContextData__thirdPartySrcAndBuildFolders", isFilename = True)

        self.panelKDevelop = xrc.XRCCTRL(self.frame, "panelKDevelop")
        self.noteBook = xrc.XRCCTRL(self.frame, "noteBook")
        self.noteBook.SetSelection(0)
        
        self.panelSelectProjects = xrc.XRCCTRL(self.frame, "panelSelectProjects")
        self.statusBar = xrc.XRCCTRL(self.frame, "statusBar")

        self.panelContext = xrc.XRCCTRL(self.frame, "panelContext")
        self.panelOptions = xrc.XRCCTRL(self.frame, "panelOptions")

        self.frame.Bind(wx.EVT_BUTTON, SelectFolderCallback("Select Binary Folder", self.GetBuildFolder, self.SetBuildFolder, self), id=xrc.XRCID("btnSelectBuildFolder"))
        self.frame.Bind(wx.EVT_BUTTON, SelectFolderCallback("Select Install Folder", self.GetInstallFolder, self.SetInstallFolder, self), id=xrc.XRCID("btnSelectInstallFolder"))
        self.frame.Bind(wx.EVT_BUTTON, SelectFolderCallback("Select folder for saving the KDevelop project file", self.GetKDevelopProjectFolder, self.SetKDevelopProjectFolder, self), id=xrc.XRCID("btnSelectKDevelopProjectFolder"))
        self.frame.Bind(wx.EVT_BUTTON, SelectFolderCallback("Add root folder", self.GetLastRootFolder, self.AddRootFolder, self), id=xrc.XRCID("btnAddRootFolder"))

        self.frame.Bind(wx.EVT_BUTTON, self.OnDetectRootFolders, id=xrc.XRCID("btnDetectRootFolders"))

        self.frame.Bind(wx.EVT_BUTTON, self.OnAddThirdPartySrcAndBuildFolder, id=xrc.XRCID("btnAddThirdPartySrcAndBuildFolder"))
        self.frame.Bind(wx.EVT_BUTTON, self.OnRemoveThirdPartySrcAndBuildFolder, id=xrc.XRCID("btnRemoveThirdPartySrcAndBuildFolder"))
        self.frame.Bind(wx.EVT_BUTTON, self.OnMoveUpThirdPartySrcAndBuildFolder, id=xrc.XRCID("btnMoveUpThirdPartySrcAndBuildFolder"))
        self.frame.Bind(wx.EVT_BUTTON, self.OnMoveDownThirdPartySrcAndBuildFolder, id=xrc.XRCID("btnMoveDownThirdPartySrcAndBuildFolder"))
        self.frame.Bind(wx.EVT_BUTTON, self.OnConfigureThirdPartySrcAndBuildFolder, id=xrc.XRCID("btnConfigureThirdPartySrcAndBuildFolder"))

        self.frame.Bind(wx.EVT_BUTTON, self.OnSetCMakePath, id=xrc.XRCID("btnSetCMakePath"))
        self.frame.Bind(wx.EVT_BUTTON, self.OnSetPythonPath, id=xrc.XRCID("btnSetPythonPath"))
        self.frame.Bind(wx.EVT_BUTTON, self.OnSelectCSnakeFile, id=xrc.XRCID("btnSelectCSnakeFile"))
        self.frame.Bind(wx.EVT_BUTTON, self.OnSetVisualStudioPath, id=xrc.XRCID("btnSetVisualStudioPath"))

        self.frame.Bind(wx.EVT_BUTTON, self.OnRefreshProjects, id=xrc.XRCID("btnForceRefreshProjects"))
        self.btnForceRefreshProjects = xrc.XRCCTRL(self.frame, "btnForceRefreshProjects")
        
        self.frame.Bind(wx.EVT_BUTTON, self.OnRemoveRootFolder, id=xrc.XRCID("btnRemoveRootFolder"))
        self.frame.Bind(wx.EVT_COMBOBOX, self.OnSelectRecentlyUsed, id=xrc.XRCID("cmbCSnakeFile"))
        self.frame.Bind(wx.EVT_BUTTON, self.OnUpdateListOfTargets, id=xrc.XRCID("btnUpdateListOfTargets"))
        self.frame.Bind(wx.EVT_BUTTON, self.OnCreateCMakeFilesAndRunCMake, id=xrc.XRCID("btnCreateCMakeFilesAndRunCMake"))
        self.frame.Bind(wx.EVT_BUTTON, self.OnConfigureALL, id=xrc.XRCID("btnConfigureALL"))
        self.frame.Bind(wx.EVT_BUTTON, self.OnConfigureThirdPartyFolder, id=xrc.XRCID("btnConfigureThirdPartyFolder"))
        self.frame.Bind(wx.EVT_BUTTON, self.OnInstallFilesToBuildFolder, id=xrc.XRCID("btnInstallFilesToBuildFolder"))
        self.frame.Bind(wx.EVT_BUTTON, self.OnLaunchIDE, id=xrc.XRCID("btnLaunchIDE"))
        self.frame.Bind(wx.EVT_NOTEBOOK_PAGE_CHANGED, self.OnNoteBookPageChanged, id=xrc.XRCID("noteBook"))
        self.frame.Bind(wx.EVT_COMBOBOX, self.OnSelectCompiler, id=xrc.XRCID("cmbCompiler"))
        
        self.frame.Bind(wx.EVT_LISTBOX_DCLICK, self.OnRootFoldersDClick, id=xrc.XRCID("lbxRootFolders"))
        self.frame.Bind(wx.EVT_LISTBOX_DCLICK, self.OnThirdPartyFoldersDClick, id=xrc.XRCID("lbxThirdPartyFolders"))
        self.frame.Bind(wx.EVT_LISTBOX_DCLICK, self.OnThirdPartyBuildFoldersDClick, id=xrc.XRCID("lbxThirdPartyBuildFolders"))
        
        if sys.platform != 'win32':
            #xrc.XRCCTRL(self.panelContext, "btnConfigureALL").Disable()
            xrc.XRCCTRL(self.panelContext, "btnLaunchIDE").Disable()
            xrc.XRCCTRL(self.panelOptions, "btnSetVisualStudioPath").Disable()
            xrc.XRCCTRL(self.panelOptions, "txtVisualStudioPath").Disable()
            xrc.XRCCTRL(self.panelOptions, "chkAskToLaunchVisualStudio").Disable()
        
        self.gridThirdPartySrcAndBuildFolders.CreateGrid(0,2)
        self.gridThirdPartySrcAndBuildFolders.SetColLabelValue(0, "Source folder")
        self.gridThirdPartySrcAndBuildFolders.SetColLabelValue(1, "Build folder")
        self.gridThirdPartySrcAndBuildFolders.Bind(wx.grid.EVT_GRID_SELECT_CELL, self.OnThirdPartySrcAndBuildFolderSelectCell)
        
        attrThirdPartySrc = wx.grid.GridCellAttr()
        attrThirdPartySrc.SetEditor(PathPickerEditor(folderName = "Third Party Source Folder"))
        attrThirdPartyBin = wx.grid.GridCellAttr()
        attrThirdPartyBin.SetEditor(PathPickerEditor(folderName = "Third Party Build Folder"))
        self.gridThirdPartySrcAndBuildFolders.SetColAttr(0, attrThirdPartySrc)
        self.gridThirdPartySrcAndBuildFolders.SetColAttr(1, attrThirdPartyBin)
        self.gridThirdPartySrcAndBuildFolders.ForceRefresh()

    def OnRootFoldersDClick(self, event):
        """Handles the wx.EVT_LISTBOX_DCLICK event for lbxRootFolders"""
        if csnUtility.IsRunningOnWindows():
            folder_path = csnUtility.UnNormalizePath( self.lbxRootFolders.GetStringSelection() )
            os.system("explorer " + folder_path)

    def OnThirdPartyFoldersDClick(self, event):
        """Handles the wx.EVT_LISTBOX_DCLICK event for lbxThirdPartyFolders"""
        if csnUtility.IsRunningOnWindows():
            folder_path = csnUtility.UnNormalizePath( self.lbxThirdPartyFolders.GetStringSelection() )
            os.system("explorer " + folder_path)

    def OnThirdPartyBuildFoldersDClick(self, event):
        """Handles the wx.EVT_LISTBOX_DCLICK event for lbxThirdPartyBuildFolders"""
        if csnUtility.IsRunningOnWindows():
            folder_path = csnUtility.UnNormalizePath( self.lbxThirdPartyBuildFolders.GetStringSelection() )
            os.system("explorer " + folder_path)
        
    def OnNoteBookPageChanged(self, event):
        if self.noteBook.GetPageText(self.noteBook.GetSelection()) == "Select Projects":
            self.DoActions([self.ActionSelectProjects])
        
    def EnableConfigBar(self, enable):
        if enable:
            xrc.XRCCTRL(self.panelContext, "btnCreateCMakeFilesAndRunCMake").Enable()
            xrc.XRCCTRL(self.panelContext, "btnInstallFilesToBuildFolder").Enable()  
            xrc.XRCCTRL(self.panelContext, "btnConfigureThirdPartyFolder").Enable()
        else:
            xrc.XRCCTRL(self.panelContext, "btnCreateCMakeFilesAndRunCMake").Disable()
            xrc.XRCCTRL(self.panelContext, "btnInstallFilesToBuildFolder").Disable() 
            xrc.XRCCTRL(self.panelContext, "btnConfigureThirdPartyFolder").Disable()
            
    def InitMenu(self):
        # File
        self.frame.Bind(wx.EVT_MENU, self.OnContextOpen, id=xrc.XRCID("mnuContextOpen"))
        self.frame.Bind(wx.EVT_MENU, self.OnContextSave, id=xrc.XRCID("mnuContextSave"))
        self.frame.Bind(wx.EVT_MENU, self.OnContextSaveAs, id=xrc.XRCID("mnuContextSaveAs"))
        self.frame.Bind(wx.EVT_MENU, self.OnExit, id=xrc.XRCID("mnuExit"))
        # Help
        self.frame.Bind(wx.EVT_MENU, self.OnHelp, id=xrc.XRCID("mnuHelp"))
        self.frame.Bind(wx.EVT_MENU, self.OnAbout, id=xrc.XRCID("mnuAbout"))
        
    def InitOtherGUIStuff(self):
        # connect close event
        self.frame.Bind(wx.EVT_CLOSE, self.OnExit, self.frame)
        
        #self.frame.GetSizer().Remove(xrc.XRCID(self.frame, "boxInstallFolder"))
        self.frame.Show()
        
        # progress bar
        self.__progressBar = None
        # progress start and range (in case of multiple actions)
        self.__progressStart = 0
        self.__progressRange = 100
        
    def Initialize(self):
        """
        Initializes the application.
        """
        self.LoadIcon()
        self.ParseCommandLine()
        self.PrintWelcomeMessages()
        self.CreateHandler()
        self.InitializeOptions()
        
        self.panelSelectProjects.SetScrollRate(25, 25)

        # load previously saved context
        contextToLoad = self.options.GetContextFilename()
        if len(self.commandLineArgs) >= 1:
            contextToLoad = self.commandLineArgs[0]
        self.LoadContext(contextToLoad)

        self.InitializePaths()
        self.UpdateGUI()
        
    def Warn(self, message):
        """ Shows a warning message to the user. ToDo: do some more fancy than print."""
        if message is None:
            return
        self.textLog.WriteText(message + "\n")
        
    def Error(self, message):
        """ Shows an error message to the user. ToDo: do some more fancy than print."""
        if message is None:
            return
        self.textLog.WriteText(message + "\n")

    def Report(self, message):
        if message is None:
            return
        self.textLog.WriteText(message + "\n")

    def SetStatus(self, message):
        self.statusBar.SetFields([message])
        
    def __SetContextFilename(self, filename):
        self.contextFilename = filename
        # also save it in the options
        self.options.SetContextFilename(filename)
        self.SaveOptions()
        # update the frame title
        self.frame.SetTitle("CSnake GUI - %s" % filename)

    def __GetContextFilename(self):
        return self.contextFilename
    
    def SetContextModified(self, modified):
        # check if new context is different from the original one
        if self.originalContextData != None:
            equal = self.context.GetData().Equal(self.originalContextData)
            if modified and equal:
                self.contextModified = False
            elif not modified and not equal:
                self.contextModified = False
            else:
                self.contextModified = modified
        else:
            self.contextModified = modified
        # update the frame title
        oldTitle = self.frame.GetTitle()
        if self.contextModified:
            if oldTitle[len(oldTitle)-1] != '*':
                self.frame.SetTitle("%s*" % oldTitle)
        else:
            if oldTitle[len(oldTitle)-1] == '*':
                self.frame.SetTitle(oldTitle[0:len(oldTitle)-1])
        # update project update flag
        if modified:
            self.projectNeedUpdate = True
            self.EnableConfigBar(True)      
        
    def IsContextModified(self):
        return self.contextModified
    
    def DoProjectNeedUpdate(self):
        return self.projectNeedUpdate
    
    def LoadIcon(self):
        iconFile = csnUtility.GetRootOfCSnake() + "/resources/Laticauda_colubrina.ico"
        icon1 = wx.Icon(iconFile, wx.BITMAP_TYPE_ICO)
        self.frame.SetIcon(icon1)
    
    def ParseCommandLine(self):
        parser = OptionParser()
        parser.add_option("-c", "--console", dest="console", default=False, help="print all messages to the console window")
        (self.commandLineOptions, self.commandLineArgs) = parser.parse_args()
        # if the csnake folder does not exist use the folder where it is run
        self.thisFolder = "%s" % (os.path.dirname(sys.argv[0]))
        self.thisFolder = self.thisFolder.replace("\\", "/")
        if self.thisFolder == "":
            self.thisFolder = "."
        if not os.path.isdir(self.csnakeFolder):
            self.csnakeFolder = self.thisFolder
    
    def PrintWelcomeMessages(self):
        self.Report("CSnake version = %s" % csnBuild.version)

    def CreateHandler(self):
        self.handler = csnGUIHandler.Handler()
        self.handler.AddListener(self.progressListener)
        self.context = None
    
    def InitializePaths(self):
        # found flags
        foundCmake = False
        foundPython = False
        foundIde = False
        # original paths
        cmakePath = self.context.GetCmakePath()
        pythonPath = self.context.GetPythonPath()
        idePath = self.context.GetIdePath()
        # find cmake if not specified
        if not os.path.isfile(cmakePath):
            cmakePath = csnUtility.GetDefaultCMakePath()
            if cmakePath:
                foundCmake = True
            else:
                self.__logger.info("Could not find default CMake.")
        # find python if not specified
        if not os.path.isfile(pythonPath):
            pythonPath = csnUtility.GetDefaultPythonPath()
            if pythonPath:
                foundPython = True
            else:
                self.__logger.info("Could not find default Python.")
        # find visual studio if not specified
        if sys.platform == 'win32' and \
            self.context.GetCompilername().find("Visual Studio") != -1 and \
            not os.path.isfile(idePath):
            idePath = csnUtility.GetDefaultVisualStudioPath(self.context.GetCompilername())
            if idePath:
                foundIde = True
            else:
                self.__logger.info("Could not find default Visual Studio.")
        # mention it to the user
        if foundCmake or foundPython or foundIde:
            message = "CSnake found paths to settings in the registry. Use them?"
            dlg = wx.MessageDialog(self.frame, message, 'Question', style = wx.YES_NO | wx.ICON_QUESTION)
            if dlg.ShowModal() == wx.ID_YES:
                self.context.SetCmakePath(cmakePath)
                self.context.SetPythonPath(pythonPath)
                if( foundIde ):
                    self.context.SetIdePath(idePath)
    
    def InitializeOptions(self):
        """ Initialize GUI options. """
        # create object
        self.options = csnGUIOptions.Options()
        self.binder.SetBuddyClass("options", self.options)
        
        # find the file
        optionsInCSnake = "%s/options" % self.csnakeFolder
        optionsInThis = "%s/options" % self.thisFolder
        # options are in the thisFolder, copy them to the csnakeFolder
        if not os.path.isfile(optionsInCSnake) and os.path.isfile(optionsInThis):
            shutil.copy(optionsInThis, optionsInCSnake)
        
        # save the file name
        self.optionsFilename = optionsInCSnake
        
        # load it if present
        if os.path.isfile(optionsInCSnake):
            try:
                self.options.Load(self.optionsFilename)
            except IOError, error:
                self.Error("%s" % error)
            
    def CopyGUIToContextAndOptions(self):
        """ Copy all GUI fields to the current context """
        self.binder.UpdateBuddies()
        
    def SaveContextAs(self):
        dlg = wx.FileDialog(None, "Save As...", defaultDir = os.path.dirname(self.options.GetContextFilename()), wildcard = "*.CSnakeGUI", style = wx.FD_SAVE)
        if dlg.ShowModal() == wx.ID_OK:
            # Add default extension if not present
            (root, ext) = os.path.splitext(dlg.GetPath())
            if ext == ".CSnakeGUI":
                contextFilename = dlg.GetPath()
            else:
                contextFilename = "%s.CSnakeGUI" % root
            # Save the context
            self.SaveContext(contextFilename)
            # the context was properly saved
            return True
        else:
            # the context was not saved
            return False
    
    def SaveContext(self, contextFilename):
        """ Save the current context. """
        # Get content from frame
        self.CopyGUIToContextAndOptions()
        # save the file name in the options
        self.options.SetContextFilename(contextFilename)
        # Try to save
        try:
            self.context.Save(self.options.GetContextFilename())
            self.frame.SetTitle("CSnake GUI - %s" % self.options.GetContextFilename())
        except:
            self.Error("Sorry, CSnakeGUI could not save the context to %s\n. Please check if another program is locking this file.\n" % self.options.GetContextFilename())
        # Update name and flag    
        self.__SetContextFilename(contextFilename)
        # Save a copy
        self.originalContextData = copy.deepcopy(self.context.GetData())
        # reset modified flag
        self.SetContextModified(False)
    
    def SaveOptions(self):
        try:
            self.options.Save(self.optionsFilename)
        except:
            self.Error("Sorry, CSnakeGUI could not save the options to %s\n. Please check if another program is locking this file.\n" % self.optionsFilename)
    
    def OnDetectRootFolders(self, event):
        if self.context.GetCsnakeFile() != None and os.path.isfile(self.context.GetCsnakeFile()):
            additionalRootFolders = self.handler.FindAdditionalRootFolders()
            self.context.ExtendRootFolders(additionalRootFolders)
            self.UpdateGUI()
        else:
            message = "Please provide a valid CSnake file."
            wx.MessageDialog(self.frame, message, 'Warning', style = wx.OK | wx.ICON_EXCLAMATION).ShowModal()
    
    def FindAdditionalRootFolders(self, onlyForNewInstance=False):
        if onlyForNewInstance and self.context.IsCSnakeFileInRecentlyUsed():
            return
        
        additionalRootFolders = self.handler.FindAdditionalRootFolders()
        if len(additionalRootFolders):
            message =  "CSnakeGUI found additional root folders which are likely to be necessary for target %s.\n" % self.context.GetInstance()
            message += "Should CSnakeGUI add the following root folders?\n\n"
            for folder in additionalRootFolders:
                message += folder + "\n"
            message += "\n\nThis question will not appear again for this target, but you can later add the above root folders\nusing the Detect button\n"
                
            dlg = wx.MessageDialog(self.frame, message, 'Question', style = wx.YES_NO | wx.ICON_QUESTION)
            if dlg.ShowModal() == wx.ID_YES:
                self.context.ExtendRootFolders(additionalRootFolders)
                self.UpdateGUI()
            
    def OnConfigureALL(self, event):
        actions = [
           self.ActionConfigureThirdPartyFolder,
           self.ActionBuildThirdParty,
           self.ActionCreateCMakeFilesAndRunCMake,
           self.ActionBuildProject,
           self.ActionInstallFilesToBuildFolder]
        self.DoActions(actions)
        
    def OnUpdateListOfTargets(self, event): # wxGlade: CSnakeGUIFrame.<event_handler>
        # check situation
        if self.context.GetCsnakeFile() == None or not os.path.isfile(self.context.GetCsnakeFile()):
            message = "Please provide a valid CSnake file."
            wx.MessageDialog(self.frame, message, 'Warning', style = wx.OK | wx.ICON_EXCLAMATION).ShowModal()
            return
        # run the action
        if self.DoActions([self.ActionUpdateListOfTargets]):
            self.UpdateGUI()
            self.EnableConfigBar(True)

    def OnCreateCMakeFilesAndRunCMake(self, event):
        # check situation
        if self.context.GetCsnakeFile() == None or not os.path.isfile(self.context.GetCsnakeFile()):
            message = "Please provide a valid CSnake file."
            wx.MessageDialog(self.frame, message, 'Warning', style = wx.OK | wx.ICON_EXCLAMATION).ShowModal()
            return
        # run the action
        if self.DoActions([self.ActionCreateCMakeFilesAndRunCMake]):
            xrc.XRCCTRL(self.panelContext, "btnLaunchIDE").SetFocus()
            xrc.XRCCTRL(self.panelContext, "btnCreateCMakeFilesAndRunCMake").Disable()
        
    def OnConfigureThirdPartyFolder(self, event):
        # check situation
        if self.context.GetCsnakeFile() == None or not os.path.isfile(self.context.GetCsnakeFile()):
            message = "Please provide a valid CSnake file."
            wx.MessageDialog(self.frame, message, 'Warning', style = wx.OK | wx.ICON_EXCLAMATION).ShowModal()
            return
        # run the action
        if self.DoActions([self.ActionConfigureThirdPartyFolder]):
            xrc.XRCCTRL(self.panelContext, "btnInstallFilesToBuildFolder").SetFocus()
            xrc.XRCCTRL(self.panelContext, "btnConfigureThirdPartyFolder").Disable()
        
    def OnInstallFilesToBuildFolder(self, event):
        # check situation
        if self.context.GetCsnakeFile() == None or not os.path.isfile(self.context.GetCsnakeFile()):
            message = "Please provide a valid CSnake file."
            wx.MessageDialog(self.frame, message, 'Warning', style = wx.OK | wx.ICON_EXCLAMATION).ShowModal()
            return
        # run the action
        if self.DoActions([self.ActionInstallFilesToBuildFolder]):
            xrc.XRCCTRL(self.panelContext, "btnCreateCMakeFilesAndRunCMake").SetFocus()
            xrc.XRCCTRL(self.panelContext, "btnInstallFilesToBuildFolder").Disable()

    def ActionUpdateListOfTargets(self):
        self.listOfPossibleTargets = self.handler.GetListOfPossibleTargets()
        if len(self.listOfPossibleTargets):
            self.context.SetInstance(self.listOfPossibleTargets[0])
            return True
        return False

    def ActionCreateCMakeFilesAndRunCMake(self):
        self.FindAdditionalRootFolders(True)
        if self.handler.ConfigureProjectToBuildFolder(_alsoRunCMake = True):
            if self.context.GetInstance().lower() == "gimias":
                self.ProposeToDeletePluginDlls(self.handler.GetListOfSpuriousPluginDlls(_reuseInstance = True))
            return True
        return False
        
    def ActionOnlyCreateCMakeFiles(self):
        self.FindAdditionalRootFolders(True)
        if self.handler.ConfigureProjectToBuildFolder(_alsoRunCMake = False):
            if self.context.GetInstance().lower() == "gimias":
                self.ProposeToDeletePluginDlls(self.handler.GetListOfSpuriousPluginDlls(_reuseInstance = True))
            return True
        return False
        
    def ActionConfigureThirdPartyFolder(self):
        if self.handler.ConfigureThirdPartyFolders():
            if self.options.GetAskToLaunchIDE():
                self.AskToLaunchIDE(self.handler.GetThirdPartySolutionPaths()[0])
            return True
        return False
        
    def ActionBuildThirdParty(self):
        return self.handler.BuildMultiple(self.handler.GetThirdPartySolutionPaths(), self.context.GetConfigurationName(), True)
        
    def ActionBuildProject(self):
        return self.handler.Build(self.handler.GetTargetSolutionPath(), self.context.GetConfigurationName(), False)
        
    def ActionInstallFilesToBuildFolder(self):
        self.FindAdditionalRootFolders(True)
        return self.handler.InstallBinariesToBuildFolder()
            
    def DoActions(self, actions):
        self.SetStatus("Processing...")
        self.textLog.Refresh()
        self.textLog.Update()
        
        self.Report("\nWorking, patience please...")
        startTime = time.time()
        
        # progress bar
        # The initial message seems to fix the window size...
        self.__progressBar = wx.ProgressDialog("Running...", "Running actions from a list of actions.", parent=self.frame, style=wx.PD_CAN_ABORT|wx.PD_AUTO_HIDE|wx.PD_APP_MODAL)

        res = True
        nActions = len(actions)
        count = 0
        range = 100 / nActions
        for action in actions:
            # progress
            start = count*range
            self.SetProgressStartAndRange(start, range)
            # remove the first 'Action'
            actionStr = action.__name__[6:]
            # split at upper case
            actionStr = re.sub(r'([a-z]*)([A-Z])',r'\1 \2',actionStr).strip()
            self.Report("Action: %s." % actionStr)
            self.ProgressChanged(ProgressEvent(self,start,actionStr))
            try:
                res = res and action()
                count += 1
            except StandardError, message:
                self.Error(str(message))
                dlg = wx.MessageDialog(self.frame, "%s" % message, 'Error', style = wx.OK | wx.ICON_ERROR)
                dlg.ShowModal()
            # check cancel
            self.ProgressChanged(ProgressEvent(self, range))
            if self.__HasUserCanceled():
                self.__ResetUserCancel()
                self.Report("Stopped: user canceled.")
                break
            if not res:
                self.Error("Stopped: Error in process.")
                break
            
        elapsedTime = time.time() - startTime
        self.Report("Done (%d seconds)." % elapsedTime)
        self.UpdateGUI()
        self.SetStatus("")
        
        self.ProgressChanged(ProgressEvent(self,100,"Done"))
        
        return res
        
    def Restart(self):
        """ Restart the application """
        arglist = []
        if( os.path.splitext(os.path.basename(sys.executable))[0].lower() == "python" ):
            arglist = [sys.executable]
            arglist.extend(sys.argv)
        os.execv(sys.executable, arglist)
                
    def OnSelectCSnakeFile(self, event): # wxGlade: CSnakeGUIFrame.<event_handler>
        """
        Select file containing the project that should be configured.
        """
        # Set path of that file that was selected before
        oldValue = self.context.GetCsnakeFile()
        if oldValue.find("/") == -1:
            oldPath = ""
        else:
            oldPathAndFilenameSplit = oldValue.rsplit("/", 1)
            oldPath = oldPathAndFilenameSplit[0] + "/"
            oldValue = oldPathAndFilenameSplit[1]

        dlg = wx.FileDialog(None, "Select CSnake file", wildcard = "Python source files (*.py)|*.py",defaultDir = oldPath, defaultFile = oldValue)
        
        if dlg.ShowModal() == wx.ID_OK:
            self.context.SetCsnakeFile(dlg.GetPath())
            self.OnUpdateListOfTargets(event)
            self.UpdateGUI()

    def SetBuildFolder(self, folder):
        self.context.SetBuildFolder(folder)
        
    def GetBuildFolder(self):
        return self.context.GetBuildFolder()
        
    def SetInstallFolder(self, folder):
        self.context.SetInstallFolder(folder)

    def GetInstallFolder(self):
        return self.context.GetInstallFolder()
        
    def SetKDevelopProjectFolder(self, folder):
        self.context.SetKdevelopProjectFolder(folder)
        
    def GetKDevelopProjectFolder(self):
        return self.context.GetKdevelopProjectFolder()
            
    def AddRootFolder(self, folder): # wxGlade: CSnakeGUIFrame.<event_handler>
        """
        Add folder where CSnake files must be searched to context rootFolders.
        """
        try:
            self.context.AddRootFolder( folder )
            
            # Automatically find thirdparty folder
            defaultThirdPartyFolder = folder + "/../thirdParty/"
            defaultThirdPartyFolder = csnUtility.NormalizePath( defaultThirdPartyFolder )
            if not os.path.isdir( defaultThirdPartyFolder ):
                defaultThirdPartyFolder = folder + "/thirdparties/"
                defaultThirdPartyFolder = csnUtility.NormalizePath( defaultThirdPartyFolder )

            if os.path.isdir( defaultThirdPartyFolder ):
                message = "Found thirdparty folder: %s. Do you want to add it?" % defaultThirdPartyFolder
                dlg = wx.MessageDialog(self.frame, message, 'Question', style = wx.YES_NO | wx.ICON_QUESTION)
                if dlg.ShowModal() == wx.ID_YES:
                    self.AddThirdPartyFolder( defaultThirdPartyFolder )
        except Exception, message:
            mes = "%s" % message
            dlg = wx.MessageDialog(self.frame, mes, 'Error', style = wx.OK | wx.ICON_ERROR)
            dlg.ShowModal()
    
    
    def GetLastRootFolder(self):
        if self.context.GetNumberOfRootFolders() > 0:
            return self.context.GetRootFolder(self.context.GetNumberOfRootFolders()-1)
        else:
            return ""

    def OnRemoveRootFolder(self, event): # wxGlade: CSnakeGUIFrame.<event_handler>
        """
        Remove folder where CSnake files must be searched from context rootFolders.
        """
        folder = self.lbxRootFolders.GetStringSelection()
        # check if correct selection
        if folder == None or folder == "":
            message = "Please select at least one folder."
            wx.MessageDialog(self.frame, message, 'Warning', style = wx.OK | wx.ICON_EXCLAMATION).ShowModal()
        else:
            # remove
            self.context.RemoveRootFolder(folder)
            self.UpdateGUI()

    def AddThirdPartyFolder(self, folder): # wxGlade: CSnakeGUIFrame.<event_handler>
        """
        Add folder where CSnake files must be searched to context.thirdPartyFolders.
        """
        defaultBuildThirdPartyFolder = self.context.GetBuildFolder() + "/thirdParty"
        message = "Do you want to use \"%s\" as Build Folder for Third Party folder \"%s\"?" % (defaultBuildThirdPartyFolder, folder)
        dlg = wx.MessageDialog(self.frame, message, 'Question', style = wx.YES_NO | wx.ICON_QUESTION)
        if dlg.ShowModal() == wx.ID_YES:
            self.context.AddThirdPartySrcAndBuildFolder(folder, defaultBuildThirdPartyFolder)
        else:
            self.context.AddThirdPartySrcAndBuildFolder(folder, "")

    def OnThirdPartySrcAndBuildFolderSelectCell(self, event):
        self.gridThirdPartySrcAndBuildFolders.SelectRow(event.GetRow())
        event.Skip()
    
    def ThirdPartySrcAndBuildFolderGetSelectedRows(self):
        selection = self.gridThirdPartySrcAndBuildFolders.GetSelectedRows()
        return selection

    def OnAddThirdPartySrcAndBuildFolder(self, event):
        self.context.AddThirdPartySrcAndBuildFolder("", "")
        self.UpdateGUI()
        self.gridThirdPartySrcAndBuildFolders.ClearSelection()
        newRow = self.gridThirdPartySrcAndBuildFolders.GetTable().GetNumberRows()-1
        self.gridThirdPartySrcAndBuildFolders.SelectRow(newRow, True)
        self.gridThirdPartySrcAndBuildFolders.SetGridCursor(newRow, 0)
        self.gridThirdPartySrcAndBuildFolders.SetFocus()

    def OnRemoveThirdPartySrcAndBuildFolder(self, event):
        selection = self.ThirdPartySrcAndBuildFolderGetSelectedRows()
        if (len(selection) == 0):
            message = "Please select at least one row. You can click on the row index to select a row."
            wx.MessageDialog(self.frame, message, 'Warning', style = wx.OK | wx.ICON_EXCLAMATION).ShowModal()
        else:
            for i in range(len(selection)):
                self.context.RemoveThirdPartySrcAndBuildFolderByIndex(selection[i])
                for j in range(i+1, len(selection)):
                    if selection[j] > selection[i]:
                        selection[j] = selection[j] - 1
            self.UpdateGUI()
            self.gridThirdPartySrcAndBuildFolders.ClearSelection()
            
        self.gridThirdPartySrcAndBuildFolders.SetFocus()
        
    def OnConfigureThirdPartySrcAndBuildFolder(self, event):
        selection = sorted(self.ThirdPartySrcAndBuildFolderGetSelectedRows())
        if (len(selection) == 0):
            message = "Please select at least one row. You can click on the row index to select a row."
            wx.MessageDialog(self.frame, message, 'Warning', style = wx.OK | wx.ICON_EXCLAMATION).ShowModal()
            self.gridThirdPartySrcAndBuildFolders.SetFocus()
        else:
            self.gridThirdPartySrcAndBuildFolders.SetFocus()
            for row in selection:
                source = self.context.GetThirdPartyFolder(row)
                build = self.context.GetThirdPartyBuildFolderByIndex(row)
                self.handler.ConfigureThirdPartyFolder( source, build, allBuildFolders = self.context.GetThirdPartyBuildFoldersComplete() )
        
    def OnMoveUpThirdPartySrcAndBuildFolder(self, event):
        selection = sorted(self.ThirdPartySrcAndBuildFolderGetSelectedRows())
        if (len(selection) == 0):
            message = "Please select at least one row. You can click on the row index to select a row."
            wx.MessageDialog(self.frame, message, 'Warning', style = wx.OK | wx.ICON_EXCLAMATION).ShowModal()
        else:
            newSelection = []
            boundaryIndex = 0
            for index in selection:
                if index > boundaryIndex:
                    self.context.MoveUpThirdPartySrcAndBuildFolder(index)
                    newSelection.append(index-1)
                else:
                    boundaryIndex = index + 1
                    newSelection.append(index)
            self.UpdateGUI()
            self.gridThirdPartySrcAndBuildFolders.ClearSelection()
            first = True
            for row in newSelection:
                self.gridThirdPartySrcAndBuildFolders.SelectRow(row, True)
                if first:
                    self.gridThirdPartySrcAndBuildFolders.SetGridCursor(row, 0)
                    first = False
                    
        self.gridThirdPartySrcAndBuildFolders.SetFocus()
        
    def OnMoveDownThirdPartySrcAndBuildFolder(self, event):
        selection = sorted(self.ThirdPartySrcAndBuildFolderGetSelectedRows(), reverse = True)
        if (len(selection) == 0):
            message = "Please select at least one row. You can click on the row index to select a row."
            wx.MessageDialog(self.frame, message, 'Warning', style = wx.OK | wx.ICON_EXCLAMATION).ShowModal()
        else:
            newSelection = []
            boundaryIndex = self.context.GetNumberOfThirdPartyFolders() - 1
            for index in selection:
                if index < boundaryIndex:
                    self.context.MoveDownThirdPartySrcAndBuildFolder(index)
                    newSelection.append(index+1)
                else:
                    boundaryIndex = index - 1
                    newSelection.append(index)
            self.UpdateGUI()
            self.gridThirdPartySrcAndBuildFolders.ClearSelection()
            first = True
            for row in newSelection:
                self.gridThirdPartySrcAndBuildFolders.SelectRow(row, True)
                if first:
                    self.gridThirdPartySrcAndBuildFolders.SetGridCursor(row, 0)
                    first = False
            
        self.gridThirdPartySrcAndBuildFolders.SetFocus()
        
    def OnContextOpen(self, event): # wxGlade: CSnakeGUIFrame.<event_handler>
        """
        Let the user load a context.
        """
        dlg = wx.FileDialog(None, "Select CSnake context file", defaultDir = os.path.dirname(self.options.GetContextFilename()), wildcard = "Context Files (*.CSnakeGUI;*.csnakecontext)|*.CSnakeGUI;*.csnakecontext|All Files (*.*)|*.*")
        if dlg.ShowModal() == wx.ID_OK:
            self.UpdateGUI()
            self.LoadContext(dlg.GetPath())

    def OnContextSave(self, event):
        """ Save the context to the current file. """
        # check if the file name is correct
        if self.contextFilename == None or self.contextFilename == "" or not os.path.exists(self.contextFilename):
            self.SaveContextAs()
        else:
            self.SaveContext(self.contextFilename)

    def OnContextSaveAs(self, event): # wxGlade: CSnakeGUIFrame.<event_handler>
        """ Let the user save the context to a specific file. """
        self.SaveContextAs()

    def GetCompilerComboBoxItems(self):
        result = []
        result.append("")
        result.append("Visual Studio 7 .NET 2003")
        result.append("Visual Studio 8 2005")
        result.append("Visual Studio 8 2005 Win64")
        result.append("Visual Studio 9 2008")
        result.append("Visual Studio 9 2008 Win64")
        result.append("KDevelop3")
        result.append("Unix Makefiles")
        result.append("Eclipse CDT4 - Unix Makefiles")
        return result
        
    def GetBuildTypeComboBoxItems(self):
        list = []
        if self.context.GetCompiler()!= None:
            list = self.context.GetCompiler().GetAllowedConfigurations()
        return list
    
    def GetCSnakeFileComboBoxItems(self):
        result = list()
        count = 0
        for x in self.context.GetRecentlyUsed():
            result.append("%s - In %s" % (x.GetInstance(), x.GetCsnakeFile()))
            count += 1
            if count >= 10:
                break
        return result
    
    def UpdateGUI(self):
        """ Refreshes the GUI based on the current context. Also saves the current context to the context filename """
        self.binder.UpdateControls()
        self.panelKDevelop.Show( self.context.GetCompiler() != None and self.context.GetCompiler().GetName() in ("KDevelop3") )
        self.frame.Layout()
        self.frame.Refresh()
        self.frame.Update()
        wx.CallAfter(self.frame.Update)
    
    def LoadContext(self, contextFilename):
        """
        Load configuration context from context filename.
        """
        # Default context
        context = csnContext.Context()
        self.handler.SetContext(context)
        loaded = False
        # Check if the file name is specified
        if contextFilename != None and contextFilename != "":
            # Check if the file exists
            if os.path.exists(contextFilename):
                # Load the context (has to be done through the handler)
                try:
                    context = self.handler.LoadContext(contextFilename)
                    loaded = True
                except IOError, error:
                    self.Error("Could not load the context file: '%s'." % error)
            else:
                self.Error("Could not find context file: '%s'." % contextFilename)
        
        # Save the context
        self.SetContext(context)
        # Save a copy
        data = self.context.GetData()
        self.originalContextData = copy.deepcopy( data )
        
        if loaded:
            # set frame title
            self.frame.SetTitle("CSnake GUI - %s" % contextFilename)
            # save file name
            self.__SetContextFilename(contextFilename)
        
        # Update 
        self.UpdateGUI()

    def SetContext(self, context):
        self.context = context
        
        self.context.AddListener(self.changeListener)
        self.binder.SetBuddyClass("context", self.context)
        
    def GetInstanceComboBoxItems(self):
        return self.listOfPossibleTargets
            
    def ProposeToDeletePluginDlls(self, spuriousDlls):
        if len(spuriousDlls) == 0:
            return
            
        dllMessage = ""
        for x in spuriousDlls:
            dllMessage += ("%s\n" % x)
            
        message = "In the build results folder, CSnake found GIMIAS plugins that have not been configured.\nThe following plugin dlls may crash GIMIAS:\n\n%s\nDelete them?" % dllMessage
        dlg = wx.MessageDialog(self.frame, message, 'Question', style = wx.YES_NO | wx.ICON_QUESTION)
        if dlg.ShowModal() != wx.ID_YES:
            return
            
        for dll in spuriousDlls:
            os.remove(dll)

    def AskToLaunchIDE(self, pathToSolution):
        message = "Launch Visual Studio with solution %s?" % pathToSolution
        dlg = wx.MessageDialog(self.frame, message, 'Question', style = wx.YES_NO | wx.ICON_QUESTION)
        if dlg.ShowModal() == wx.ID_YES:
            argList = [self.context.GetIdePath(), pathToSolution]
            subprocess.Popen(argList)

    def OnLaunchIDE(self, event = None):
        argList = [self.context.GetIdePath(), self.handler.GetTargetSolutionPath()]
        subprocess.Popen(argList)
    
    def OnExit(self, event = None):
        if not self.destroyed:
            self.CopyGUIToContextAndOptions()
            if self.IsContextModified():
                dlg = wx.MessageDialog(self.frame, "Save changes before closing?", style = wx.YES_NO | wx.CANCEL)
                ret = dlg.ShowModal()
                if ret == wx.ID_YES:
                    if self.contextFilename == None or not os.path.isfile(self.contextFilename):
                        if self.SaveContextAs():
                            self.destroyed = True
                            self.frame.Destroy()
                    else:
                        self.SaveContext(self.contextFilename)
                        self.destroyed = True
                        self.frame.Destroy()
                elif ret == wx.ID_NO:
                    self.destroyed = True
                    self.frame.Destroy()
            else:
                self.destroyed = True
                self.frame.Destroy()

    def OnHelp(self, event = None):
        ''' Text displayed for help.'''
        indexFilename = csnUtility.GetRootOfCSnake() + "/doc/html/index.html"
        if os.path.exists(indexFilename):
            webbrowser.open(indexFilename)
        else:
            dialog = wx.MessageDialog(self.frame, "Missing documentation.", 'Error', style = wx.OK | wx.ICON_ERROR)
            dialog.ShowModal()
                                        
    def OnAbout(self, event = None):
        ''' Text displayed in the About box.'''
        about = About()
        about.read(csnUtility.GetRootOfCSnake() + "/resources/about.txt")
        wx.AboutBox(about.getWxAboutDialogInfo())
        
    def OnSelectRecentlyUsed(self, event): # wxGlade: CSnakeGUIFrame.<event_handler>
        # get the context from the list
        context = self.context.GetRecentlyUsed()[event.GetSelection()]
        # update context properties
        self.context.SetCsnakeFile(context.GetCsnakeFile())
        # do an update of the targets
        self.OnUpdateListOfTargets(event)
        # force the instance
        self.context.SetInstance(context.GetInstance())
        # update frame
        self.UpdateGUI()

    def OnSetCMakePath(self, event): # wxGlade: CSnakeOptionsFrame.<event_handler>
        """
        Let the user select where CSnake is located.
        """
        dlg = wx.FileDialog(None, "Select path to CMake")
        if dlg.ShowModal() == wx.ID_OK:
            self.context.SetCmakePath(dlg.GetPath())
            self.UpdateGUI()

    def OnSetPythonPath(self, event): # wxGlade: CSnakeOptionsFrame.<event_handler>
        dlg = wx.FileDialog(None, "Select path to Python")
        if dlg.ShowModal() == wx.ID_OK:
            self.context.SetPythonPath(dlg.GetPath())
            self.UpdateGUI()

    def OnSetVisualStudioPath(self, event): # wxGlade: CSnakeOptionsFrame.<event_handler>
        dlg = wx.FileDialog(None, "Select path to Visual Studio")
        if dlg.ShowModal() == wx.ID_OK:
            self.context.SetIdePath(dlg.GetPath())
            self.UpdateGUI()

    def ActionSelectProjects(self):
        # do not go further if there is no csnake file or instance
        if not self.context.GetCsnakeFile() or not self.context.GetInstance():
            return
        
        # get list of ALL the categories on which the user can filter
        self.SetStatus("Retrieving projects...")
        
        forceRefresh = self.DoProjectNeedUpdate()
        
        if len(self.projectCheckBoxes.keys()) == 0 or forceRefresh:
            # empty the filter to get the full list
            previousFilter = self.context.GetFilter()
            self.context.SetFilter(list())
            try:
                categories = self.handler.GetCategories(forceRefresh)
            except:
                # restore saved filter
                self.context.SetFilter(previousFilter)
                # show error message
                message = "Could not load project dependencies for instance %s from file '%s'." % (self.context.GetInstance(), self.context.GetCsnakeFile())
                message = message + "\nPlease check the fields 'CSnake File' and 'Instance'"
                wx.MessageDialog(self.frame, message, 'Error', style = wx.OK | wx.ICON_ERROR).ShowModal()
                self.SetStatus("")
                return False
            # restore saved filter
            self.context.SetFilter(previousFilter)
            
            # create list of checkboxes for the categories
            self.panelSelectProjects.GetSizer().Clear()
            for category in self.projectCheckBoxes.keys():
                self.projectCheckBoxes[category].Destroy()
            self.projectCheckBoxes.clear()
            
            for category in sorted(categories):
                self.projectCheckBoxes[category] = wx.CheckBox(self.panelSelectProjects, -1, category)
                self.projectCheckBoxes[category].SetValue( not category in self.context.GetFilter() )
                self.panelSelectProjects.GetSizer().Add(self.projectCheckBoxes[category], 0, 0, 3)
                self.panelSelectProjects.Bind(wx.EVT_CHECKBOX, self.OnCategoryCheckBoxChanged, self.projectCheckBoxes[category])
    
            # create list of checkboxes for the 'super categories' (which are groups of normal categories, such as Tests)
            for super in self.context.GetSubCategoriesOf().keys():
                value = True
                for sub in self.context.GetSubCategoriesOf()[super]:
                    value = value and (not sub in self.context.GetFilter())
                        
                self.projectCheckBoxes[super] = wx.CheckBox(self.panelSelectProjects, -1, super)
                self.projectCheckBoxes[super].SetValue( value )
                self.panelSelectProjects.GetSizer().Insert(0, self.projectCheckBoxes[super], 0, 0, 3)
                self.panelSelectProjects.Bind(wx.EVT_CHECKBOX, self.OnSuperCategoryCheckBoxChanged, self.projectCheckBoxes[super])
                
            self.panelSelectProjects.GetSizer().Add(self.btnForceRefreshProjects, 0, 0, 3)
            self.panelSelectProjects.Layout()
            self.panelSelectProjects.FitInside()
            
            # update flog
            self.projectNeedUpdate = False
            
        self.SetStatus("")
        return True
        
    def OnSuperCategoryCheckBoxChanged(self, event): # wxGlade: CSnakeOptionsFrame.<event_handler>
        """ 
        Respond to checking a supercategory (such as Tests or Demos). Results in (un)checking all subcategories in that
        supercategory.
        """
        super = event.GetEventObject().GetLabel()
        value = self.projectCheckBoxes[super].GetValue()
        self.UpdateContextFilter(super, not event.IsChecked())
                
        # set the check boxes of sub categories
        for cbName in self.projectCheckBoxes.keys():
            if cbName in self.context.GetSubCategoriesOf()[super]:
                self.projectCheckBoxes[cbName].SetValue(value)
                self.UpdateContextFilter(cbName, not event.IsChecked())
                    
    def OnCategoryCheckBoxChanged(self, event): # wxGlade: Dialog.<event_handler>
        """ 
        Updates the category filter, based on the current status of the checkbox for each category.
        """
        category = event.GetEventObject().GetLabel()
        self.UpdateContextFilter(category, not event.IsChecked())
            
    def UpdateContextFilter(self, category, filterOut):
        if filterOut and not self.context.HasFilter(category):
            self.context.AddFilter(category)
        elif not filterOut and self.context.HasFilter(category):
            self.context.RemoveFilter(category)
                
    def OnSelectCompiler(self, event):
        self.context.FindCompiler()
        # find visual studio if needed
        if self.context.GetCompilername().startswith('Visual Studio'):
            idePath = csnUtility.GetDefaultVisualStudioPath(self.context.GetCompilername())
            # mention it to the user
            if idePath:
                if idePath != self.context.GetIdePath():
                    message = "CSnake found the corresponding Visual Studio in the registry. Use it?"
                    dlg = wx.MessageDialog(self.frame, message, 'Question', style = wx.YES_NO | wx.ICON_QUESTION)
                    if dlg.ShowModal() == wx.ID_YES:
                        self.context.SetIdePath(idePath)
            else:
                message = "CSnake could not find the corresponding Visual Studio in the registry."
                wx.MessageDialog(self.frame, message, 'Warning', style = wx.OK | wx.ICON_WARNING).ShowModal()
                self.context.SetIdePath("")
            
        # update the GUI
        self.UpdateGUI()
        
    def OnRefreshProjects(self, event):
        self.projectNeedUpdate = True
        self.DoActions([self.ActionSelectProjects])

    def GetLastThirdPartyFolder(self):
        return self.context.GetLastThirdPartyFolder( )

    def StateChanged(self, event):
        """ Called by the ChangeListener. """
        self.SetContextModified(True)
        
    def SetProgressStartAndRange(self, start, range):
        self.__progressRange = range
        self.__progressStart = start

    def ProgressChanged(self, event):
        """ Called by the ProgressListener. """
        if self.__progressBar and self.__progressBar.IsShown():
            progress = self.__progressStart + event.GetProgress()*self.__progressRange/100
            cont, skip = self.__progressBar.Update(progress, event.GetMessage())
            if not cont:
                self.__progressBar.Destroy()
                self.__cancelAction = True
        
    def __HasUserCanceled(self):
        return self.__cancelAction
    
    def __ResetUserCancel(self):
        self.__cancelAction = False 

if __name__ == "__main__":
    csnUtility.InitialiseLogging()
    
    logger = logging.getLogger("CSnake")
    logger.info("Starting program.")

    app = CSnakeGUIApp(0)
    app.MainLoop()
    
    logger.info("Ending program.")
