#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-
# generated by wxGlade 0.5 on Sat Sep 15 14:23:13 2007 from D:\Users\Maarten\Projects\Gimias\Prog\GIMIAS.cmake\GBuild\csnGUI.wxg

import wx
from wx import xrc
import csnGUIHandler
import csnGUIOptions
import csnContext
import csnContextConverter
import csnBuild
import csnUtility
import os.path
import sys
import shutil
import string
import time
import subprocess
import xrcbinder
from optparse import OptionParser
from about import About
import wx.grid

# Only there to allow its inclusion when generating executables.
import csnCilab #@UnusedImport
import logging.config
import webbrowser

class PathPickerCtrl(wx.Control):
    def __init__(self, parent, id=-1, pos=(-1,-1), size=(-1,-1), style=0, validator=wx.DefaultValidator, name="PathPicker", evtHandler=None, folderName="Folder"):
        wx.Control.__init__(self, parent, id=id, pos=pos, size=size, style=style|wx.BORDER_NONE, validator=validator, name=name)
        
        self.evtHandler = evtHandler
        
        self.oldValue = None
        self.grid = None
        self.row = None
        self.col = None
        self.handlerConnected = False
        self.folderName = folderName
        self.dontLeaveEditMode = False
        
        self.panel = wx.Panel(self, style = wx.BORDER_NONE)
        self.text = wx.TextCtrl(self.panel, style = wx.TE_PROCESS_TAB | wx.TE_PROCESS_ENTER)
        self.button = wx.Button(self.panel, label='...')
        self.button.SetMinSize((30, -1))
        self.panel.Bind(wx.EVT_BUTTON, self.OnButtonClick)
        
        self.sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer.Add(self.text, flag=wx.EXPAND, proportion=1)
        self.sizer.Add(self.button, flag=wx.EXPAND, proportion=0)
        self.panel.SetSizer(self.sizer)
        
        self.windows = [self, self.panel, self.text, self.button]
        for window in self.windows:
            window.Bind(wx.EVT_KILL_FOCUS, self.OnSomeoneLostFocus)
        self.Bind(wx.EVT_SET_FOCUS, self.OnGotFocus)
        self.text.Bind(wx.EVT_KEY_DOWN, self.OnKeyDown)
        self.button.Bind(wx.EVT_KEY_DOWN, self.OnKeyDown)
        
    def OnButtonClick(self, event):
        self.dontLeaveEditMode = True
        oldValue = self.text.GetValue()
        dlg = wx.DirDialog(None, "Select %s" % self.folderName, oldValue, wx.DD_DIR_MUST_EXIST)
        if dlg.ShowModal() == wx.ID_OK:
            self.text.SetValue(dlg.GetPath().replace("\\", "/"))
            self.MoveGridCursor(0, 0)
        self.dontLeaveEditMode = False
        
    def OnKeyDown(self, event):
        if event.GetKeyCode()==wx.WXK_TAB:
            self.MoveGridCursor(0, 1)
            event.Skip(False)
        elif event.GetKeyCode()==wx.WXK_RETURN:
            self.MoveGridCursor(1, 0)
            event.Skip(False)
        elif event.GetKeyCode()==wx.WXK_ESCAPE:
            self.SetValue(self.oldValue)
            self.MoveGridCursor(0, 0)
            self.grid.SetFocus()
            event.Skip(False)
        else:
            event.Skip(True)
    
    def MoveGridCursor(self, diffRow, diffCol):
        newRow = self.row + diffRow
        self.grid.SetFocus()
        if newRow >= self.grid.GetTable().GetNumberRows():
            newRow = self.row
        newCol = self.col + diffCol
        if newCol >= self.grid.GetTable().GetNumberCols():
            newCol = self.col
        self.grid.SetGridCursor(newRow, newCol)
        self.grid.ClearSelection()
        self.grid.SelectRow(newRow)
    
    def OnGotFocus(self, event):
        self.text.SetFocus()
        event.Skip()
        
    def OnSomeoneLostFocus(self, event):
        if not self.handlerConnected:
            if not (self.FindFocus() in self.windows) and not self.dontLeaveEditMode:
                self.evtHandler.ProcessEvent(event)
    
    def SetDimensions(self, x, y, width, height, sizeFlags):
        wx.Control.SetDimensions(self, x, y, width, height, sizeFlags)
        self.panel.SetDimensions(x=0, y=0, width=width, height=height, sizeFlags=sizeFlags)
    
    def SetInitialValue(self, value):
        self.oldValue = value
        self.SetValue(value)
        
    def SetValue(self, value):
        self.text.SetValue(value)
        self.text.SetInsertionPointEnd()
        
    def GetValue(self):
        return self.text.GetValue()
    
    def SetGrid(self, row, col, grid):
        self.row = row
        self.col = col
        self.grid = grid
    
class PathPickerEditor(wx.grid.PyGridCellEditor):
    def __init__(self, folderName = "Folder"):
        wx.grid.PyGridCellEditor.__init__(self)
        self.handlerConnected = False
        self.folderName = folderName
    
    def ConnectHandler(self):
        if not self.handlerConnected:
            self._picker.PushEventHandler(self.evtHandler)
            self.handlerConnected = True
            self._picker.handlerConnected = True

    def DisconnectHandler(self):
        if self.handlerConnected:
            self._picker.PopEventHandler()
            self.handlerConnected = False
            self._picker.handlerConnected = False
    
    def Create(self, parent, id, evtHandler):
        self._picker = PathPickerCtrl(parent=parent, id=id, evtHandler=evtHandler, folderName=self.folderName)
        self.value = ""
        self.SetControl(self._picker)
        self.evtHandler = evtHandler
        self.ConnectHandler()
 
    def SetSize(self, rect):
        self._picker.SetDimensions(rect.x, rect.y, rect.width, rect.height, wx.SIZE_ALLOW_MINUS_ONE)
 
    def Show(self, show, attr):
        super(PathPickerEditor, self).Show(show, attr)
 
    def PaintBackground(self, rect, attr):
        pass
 
    def BeginEdit(self, row, col, grid):
        self.DisconnectHandler()
        self.value = str(grid.GetTable().GetValue(row, col)).strip()
        self._picker.SetInitialValue(self.value)
        self._picker.SetGrid(row, col, grid)
        self._picker.SetFocus()
 
    def EndEdit(self, row, col, grid):
        changed = False
        value = self._picker.GetValue()
        if value != self.value:
            changed = True
            grid.SetCellValue(row, col, value) # update the table
            self.value = value
        self.ConnectHandler()
        return changed
 
    def Reset(self):
        pass
 
    def IsAcceptedKey(self, evt):
        return (not (evt.ControlDown() or evt.AltDown()) and
                evt.GetKeyCode() != wx.WXK_SHIFT)
 
    def StartingKey(self, evt):
        key = evt.GetKeyCode()
        if key in [ wx.WXK_NUMPAD0, wx.WXK_NUMPAD1, wx.WXK_NUMPAD2, wx.WXK_NUMPAD3,
                    wx.WXK_NUMPAD4, wx.WXK_NUMPAD5, wx.WXK_NUMPAD6, wx.WXK_NUMPAD7,
                    wx.WXK_NUMPAD8, wx.WXK_NUMPAD9
                    ]:
 
            ch = chr(ord('0') + key - wx.WXK_NUMPAD0)
            self._picker.SetValue(ch)
        elif key < 256 and key >= 0 and chr(key) in string.printable:
            ch = chr(key)
            self._picker.SetValue(ch)
        elif key in [wx.WXK_DELETE, wx.WXK_BACK]:
            self._picker.SetValue("")
        
        evt.Skip()
 
    def StartingClick(self):
        pass
 
    def Clone(self):
        return PathPickerEditor(folderName = self.folderName)

class RedirectText:
    """
    Used to redirect messages to stdout to the text control in CSnakeGUIFrame.
    """
    def __init__(self,aWxTextCtrl):
        self.out=aWxTextCtrl
        # logging init
        self.logger = logging.getLogger("CSnake")

    def write(self,string):
        self.out.WriteText(string)
        self.out.Update()
        # also write it to the log file
        log = True
        # remove spurious end-of-line
        if (len(string) == 1 and string[len(string)-1:] == '\n'):
            log = False
        # remove possible end-of-line
        if (len(string) > 0 and string[len(string)-1] == '\n'):
            string = string[0:len(string)-1]
        # print
        if log:
            self.logger.info(string)

class SelectFolderCallback:
    """ 
    Lets the user choose a path, then calls 'callback' to set the path value in the domain layer, 
    and calls app.UpdateGUIAndSaveContextAndOptions.
    """
    def __init__(self, message, callbackGet, callbackSet, app):
        self.message = message
        self.callbackGet = callbackGet
        self.callbackSet = callbackSet
        self.app = app
        
    def __call__(self, event = None):
        oldValue = self.callbackGet()
        
        dlg = wx.DirDialog(None, self.message, oldValue, wx.DD_DIR_MUST_EXIST)
        
        if dlg.ShowModal() == wx.ID_OK:
            self.callbackSet(dlg.GetPath().replace("\\", "/"))
        self.app.UpdateGUIAndSaveContextAndOptions()
        
class CSnakeGUIApp(wx.App):
    def OnInit(self):
        self.destroyed = False
        self.listOfPossibleTargets = []
        self.projectCheckBoxes = dict()
        
        wx.InitAllImageHandlers()
        xrcFile = csnUtility.GetRootOfCSnake() + "/resources/csnGUI.xrc"
        self.res = xrc.XmlResource(xrcFile)
        
        self.csnakeFolder = os.path.expanduser("~/.csnake")
        self.thisFolder = None
            
        self.InitFrame()
        self.InitMenu()
        self.InitOtherGUIStuff()
        self.Initialize()
        self.SetTopWindow(self.frame)
        return 1

    def InitFrame(self):
        self.frame = self.res.LoadFrame(None, "frmCSnakeGUI")
        self.binder = xrcbinder.Binder(self, self.frame)
        
        self.textLog = xrc.XRCCTRL(self.frame, "textLog")
        self.binder.AddTextControl("txtBuildFolder", buddyClass = "context", buddyField = "buildFolder", isFilename = True)
        self.binder.AddTextControl("txtInstallFolder", buddyClass = "context", buddyField = "installFolder", isFilename = True)
        self.binder.AddTextControl("txtKDevelopProjectFolder", buddyClass = "context", buddyField = "kdevelopProjectFolder", isFilename = True)
        self.binder.AddTextControl("txtCMakePath", buddyClass = "context", buddyField = "cmakePath", isFilename = True)
        self.binder.AddTextControl("txtPythonPath", buddyClass = "context", buddyField = "pythonPath", isFilename = True)
        self.binder.AddTextControl("txtVisualStudioPath", buddyClass = "context", buddyField = "idePath", isFilename = True)
        self.binder.AddComboBox("cmbCSnakeFile", valueListFunctor = self.GetCSnakeFileComboBoxItems, buddyClass = "context", buddyField = "csnakeFile", isFilename = True)
        self.binder.AddComboBox("cmbInstance", valueListFunctor = self.GetInstanceComboBoxItems, buddyClass = "context", buddyField = "instance")
        self.binder.AddDropDownList("cmbCompiler", valueListFunctor = self.GetCompilerComboBoxItems, buddyClass = "context", buddyField = "compilername")
        self.binder.AddDropDownList("cmbBuildType", valueListFunctor = self.GetBuildTypeComboBoxItems, buddyClass = "context", buddyField = "configurationName")
        self.binder.AddListBox("lbRootFolders", buddyClass = "context", buddyField = "rootFolders", isFilename = True)
        self.binder.AddCheckBox("chkAskToLaunchVisualStudio", buddyClass = "options", buddyField = "askToLaunchIDE")
        
        self.binder.AddGrid("lbThirdPartySrcAndBuildFolders", buddyClass = "context", buddyField = "thirdPartySrcAndBuildFolders", isFilename = True)

        self.panelKDevelop = xrc.XRCCTRL(self.frame, "panelKDevelop")
        self.noteBook = xrc.XRCCTRL(self.frame, "noteBook")
        self.noteBook.SetSelection(0)
        
        self.panelSelectProjects = xrc.XRCCTRL(self.frame, "panelSelectProjects")
        self.statusBar = xrc.XRCCTRL(self.frame, "statusBar")

        self.panelContext = xrc.XRCCTRL(self.frame, "panelContext")
        self.panelOptions = xrc.XRCCTRL(self.frame, "panelOptions")

        self.frame.Bind(wx.EVT_BUTTON, SelectFolderCallback("Select Binary Folder", self.GetBuildFolder, self.SetBuildFolder, self), id=xrc.XRCID("btnSelectBuildFolder"))
        self.frame.Bind(wx.EVT_BUTTON, SelectFolderCallback("Select Install Folder", self.GetInstallFolder, self.SetInstallFolder, self), id=xrc.XRCID("btnSelectInstallFolder"))
        self.frame.Bind(wx.EVT_BUTTON, SelectFolderCallback("Select folder for saving the KDevelop project file", self.GetKDevelopProjectFolder, self.SetKDevelopProjectFolder, self), id=xrc.XRCID("btnSelectKDevelopProjectFolder"))
        self.frame.Bind(wx.EVT_BUTTON, SelectFolderCallback("Add root folder", self.GetLastRootFolder, self.AddRootFolder, self), id=xrc.XRCID("btnAddRootFolder"))

        self.frame.Bind(wx.EVT_BUTTON, self.OnDetectRootFolders, id=xrc.XRCID("btnDetectRootFolders"))

        self.frame.Bind(wx.EVT_BUTTON, self.OnAddThirdPartySrcAndBuildFolder, id=xrc.XRCID("btnAddThirdPartySrcAndBuildFolder"))
        self.frame.Bind(wx.EVT_BUTTON, self.OnRemoveThirdPartySrcAndBuildFolder, id=xrc.XRCID("btnRemoveThirdPartySrcAndBuildFolder"))
        self.frame.Bind(wx.EVT_BUTTON, self.OnMoveUpThirdPartySrcAndBuildFolder, id=xrc.XRCID("btnMoveUpThirdPartySrcAndBuildFolder"))
        self.frame.Bind(wx.EVT_BUTTON, self.OnMoveDownThirdPartySrcAndBuildFolder, id=xrc.XRCID("btnMoveDownThirdPartySrcAndBuildFolder"))
        self.frame.Bind(wx.EVT_BUTTON, self.OnConfigureThirdPartySrcAndBuildFolder, id=xrc.XRCID("btnConfigureThirdPartySrcAndBuildFolder"))

        self.frame.Bind(wx.EVT_BUTTON, self.OnSetCMakePath, id=xrc.XRCID("btnSetCMakePath"))
        self.frame.Bind(wx.EVT_BUTTON, self.OnSetPythonPath, id=xrc.XRCID("btnSetPythonPath"))
        self.frame.Bind(wx.EVT_BUTTON, self.OnSelectCSnakeFile, id=xrc.XRCID("btnSelectCSnakeFile"))
        self.frame.Bind(wx.EVT_BUTTON, self.OnSetVisualStudioPath, id=xrc.XRCID("btnSetVisualStudioPath"))

        self.frame.Bind(wx.EVT_BUTTON, self.RefreshProjects, id=xrc.XRCID("btnForceRefreshProjects"))
        self.btnForceRefreshProjects = xrc.XRCCTRL(self.frame, "btnForceRefreshProjects")
        
        self.frame.Bind(wx.EVT_BUTTON, self.OnRemoveRootFolder, id=xrc.XRCID("btnRemoveRootFolder"))
        self.frame.Bind(wx.EVT_COMBOBOX, self.OnSelectRecentlyUsed, id=xrc.XRCID("cmbCSnakeFile"))
        self.frame.Bind(wx.EVT_BUTTON, self.OnUpdateListOfTargets, id=xrc.XRCID("btnUpdateListOfTargets"))
        self.frame.Bind(wx.EVT_BUTTON, self.OnCreateCMakeFilesAndRunCMake, id=xrc.XRCID("btnCreateCMakeFilesAndRunCMake"))
        self.frame.Bind(wx.EVT_BUTTON, self.OnConfigureALL, id=xrc.XRCID("btnConfigureALL"))
        self.frame.Bind(wx.EVT_BUTTON, self.OnConfigureThirdPartyFolder, id=xrc.XRCID("btnConfigureThirdPartyFolder"))
        self.frame.Bind(wx.EVT_BUTTON, self.OnInstallFilesToBuildFolder, id=xrc.XRCID("btnInstallFilesToBuildFolder"))
        self.frame.Bind(wx.EVT_BUTTON, self.OnLaunchIDE, id=xrc.XRCID("btnLaunchIDE"))
        self.frame.Bind(wx.EVT_NOTEBOOK_PAGE_CHANGED, self.OnNoteBookPageChanged, id=xrc.XRCID("noteBook"))
        self.frame.Bind(wx.EVT_COMBOBOX, self.OnSelectCompiler, id=xrc.XRCID("cmbCompiler"))
        
        self.frame.Bind(wx.EVT_LISTBOX_DCLICK, self.OnRootFoldersDClick, id=xrc.XRCID("lbRootFolders"))
        self.frame.Bind(wx.EVT_LISTBOX_DCLICK, self.OnThirdPartyFoldersDClick, id=xrc.XRCID("lbThirdPartyFolders"))
        self.frame.Bind(wx.EVT_LISTBOX_DCLICK, self.OnThirdPartyBuildFoldersDClick, id=xrc.XRCID("lbThirdPartyBuildFolders"))
        
        if sys.platform != 'win32':
            xrc.XRCCTRL(self.panelContext, "btnConfigureALL").Disable()
            xrc.XRCCTRL(self.panelContext, "btnLaunchIDE").Disable()
            xrc.XRCCTRL(self.panelOptions, "btnSetVisualStudioPath").Disable()
            xrc.XRCCTRL(self.panelOptions, "txtVisualStudioPath").Disable()
            xrc.XRCCTRL(self.panelOptions, "chkAskToLaunchVisualStudio").Disable()
        
        self.lbThirdPartySrcAndBuildFolders.CreateGrid(0,2)
        self.lbThirdPartySrcAndBuildFolders.SetColLabelValue(0, "Source folder")
        self.lbThirdPartySrcAndBuildFolders.SetColLabelValue(1, "Build folder")
        self.lbThirdPartySrcAndBuildFolders.Bind(wx.grid.EVT_GRID_SELECT_CELL, self.OnThirdPartySrcAndBuildFolderSelectCell)
        
        attrThirdPartySrc = wx.grid.GridCellAttr()
        attrThirdPartySrc.SetEditor(PathPickerEditor(folderName = "Third Party Source Folder"))
        attrThirdPartyBin = wx.grid.GridCellAttr()
        attrThirdPartyBin.SetEditor(PathPickerEditor(folderName = "Third Party Build Folder"))
        self.lbThirdPartySrcAndBuildFolders.SetColAttr(0, attrThirdPartySrc)
        self.lbThirdPartySrcAndBuildFolders.SetColAttr(1, attrThirdPartyBin)
        self.lbThirdPartySrcAndBuildFolders.ForceRefresh()

    def OnRootFoldersDClick(self, event):
        """Handles the wx.EVT_LISTBOX_DCLICK event for lbRootFolders"""
        if csnUtility.IsRunningOnWindows():
            folder_path = csnUtility.UnNormalizePath( self.lbRootFolders.GetStringSelection() )
            os.system("explorer " + folder_path)

    def OnThirdPartyFoldersDClick(self, event):
        """Handles the wx.EVT_LISTBOX_DCLICK event for lbRootFolders"""
        if csnUtility.IsRunningOnWindows():
            folder_path = csnUtility.UnNormalizePath( self.lbThirdPartyFolders.GetStringSelection() )
            os.system("explorer " + folder_path)

    def OnThirdPartyBuildFoldersDClick(self, event):
        """Handles the wx.EVT_LISTBOX_DCLICK event for lbRootFolders"""
        if csnUtility.IsRunningOnWindows():
            folder_path = csnUtility.UnNormalizePath( self.lbThirdPartyBuildFolders.GetStringSelection() )
            os.system("explorer " + folder_path)
        
    def OnNoteBookPageChanged(self, event):
        if self.noteBook.GetPageText(self.noteBook.GetSelection()) == "Select Projects":
            self.SelectProjects()
        
    def InitMenu(self):
        # File
        self.frame.Bind(wx.EVT_MENU, self.OnContextOpen, id=xrc.XRCID("mnuContextOpen"))
        self.frame.Bind(wx.EVT_MENU, self.OnContextCreateACopy, id=xrc.XRCID("mnuContextCreateACopy"))
        self.frame.Bind(wx.EVT_MENU, self.OnContextAbandonChanges, id=xrc.XRCID("mnuContextAbandonChanges"))
        self.frame.Bind(wx.EVT_MENU, self.OnExit, id=xrc.XRCID("mnuExit"))
        # Help
        self.frame.Bind(wx.EVT_MENU, self.OnHelp, id=xrc.XRCID("mnuHelp"))
        self.frame.Bind(wx.EVT_MENU, self.OnAbout, id=xrc.XRCID("mnuAbout"))
        
    def InitOtherGUIStuff(self):
        # connect close event
        self.frame.Bind(wx.EVT_CLOSE, self.OnExit, self.frame)
        
        #self.frame.GetSizer().Remove(xrc.XRCID(self.frame, "boxInstallFolder"))
        self.frame.Show()
        
    def Initialize(self):
        """
        Initializes the application.
        """
        self.LoadIcon()
        self.ParseCommandLine()
        if not self.commandLineOptions.console:
            self.RedirectStdOut()
        self.PrintWelcomeMessages()
        self.CreateHandler()
        self.InitializeOptions()
        
        # load previously saved context
        contextToLoad = self.options.contextFilename
        if len(self.commandLineArgs) >= 1:
            contextToLoad = self.commandLineArgs[0]
            
        if self.LoadContext(contextToLoad):
            self.BackupContextFile()

        self.panelSelectProjects.SetScrollRate(25, 25)

        self.UpdateGUIAndSaveContextAndOptions()
        
    def Warn(self, message):
        """ Shows a warning message to the user. ToDo: do some more fancy than print."""
        if message is None:
            return
        print message + "\n"
        
    def Error(self, message):
        """ Shows an error message to the user. ToDo: do some more fancy than print."""
        if message is None:
            return
        print message + "\n"

    def Report(self, message):
        if message is None:
            return
        print message + "\n"

    def BackupContextFile(self):
        """ Creates a backup of the current context, so that the user can later abandon all his changes. """
        self.contextBeforeEditingFilename = "%s/contextBeforeEditing" % self.csnakeFolder
        try:
            shutil.copy(self.options.contextFilename, self.contextBeforeEditingFilename)
        except:
            message = "Warning: could not copy %s to backup location %s" % (self.options.contextFilename, self.contextBeforeEditingFilename)
            self.Warn(message)

    def SetStatus(self, message):
        self.statusBar.SetFields([message])
        
    def LoadIcon(self):
        iconFile = csnUtility.GetRootOfCSnake() + "/resources/Laticauda_colubrina.ico"
        icon1 = wx.Icon(iconFile, wx.BITMAP_TYPE_ICO)
        self.frame.SetIcon(icon1)
    
    def ParseCommandLine(self):
        parser = OptionParser()
        parser.add_option("-c", "--console", dest="console", default=False, help="print all messages to the console window")
        (self.commandLineOptions, self.commandLineArgs) = parser.parse_args()
        # if the csnake folder does not exist use the folder where it is run
        self.thisFolder = "%s" % (os.path.dirname(sys.argv[0]))
        self.thisFolder = self.thisFolder.replace("\\", "/")
        if self.thisFolder == "":
            self.thisFolder = "."
        if not os.path.isdir(self.csnakeFolder):
            self.csnakeFolder = self.thisFolder
    
    def RedirectStdOut(self):
        # redirect std out
        self.redir=RedirectText(self.textLog)
        sys.stdout=self.redir
        sys.stderr=self.redir

    def PrintWelcomeMessages(self):
        self.Report("CSnake version = %s" % csnBuild.version)

    def CreateHandler(self):
        self.handler = csnGUIHandler.Handler()
        self.context = None
    
    def InitializeOptions(self):
        self.options = csnGUIOptions.Options()
        self.binder.SetBuddyClass("options", self.options)
        
        optionsInCSnake = "%s/options" % self.csnakeFolder
        optionsInThis = "%s/options" % self.thisFolder
        if not os.path.isfile(optionsInCSnake) and os.path.isfile(optionsInThis):
            shutil.copy(optionsInThis, optionsInCSnake)
        self.optionsFilename = optionsInCSnake
        self.converter = csnContextConverter.Converter(self.optionsFilename)
        
        # convert possible old options
        converted = False
        if os.path.exists(self.optionsFilename):
            converted = self.converter.ConvertOptions()
            
        if converted:
            self.options.Load(self.optionsFilename)
        else:
            self.options.contextFilename = "%s/default.csnakecontext" % self.csnakeFolder
            self.options.Save(self.optionsFilename)
            
        if not os.path.exists(self.options.contextFilename):
            self.options.contextFilename = "%s/context" % self.csnakeFolder
            csnContext.Context().Save(self.options.contextFilename)
        
    def CopyGUIToContextAndOptions(self):
        """ Copy all GUI fields to the current context """
        self.binder.UpdateBuddies()
        
    def SaveContextAndOptions(self, contextFilename = ""):
        """
        Copy context from the widget controls to self.context.
        If filename is not "", save current configuration context (source folder/build folder/etc) 
        to filename.
        """
        self.CopyGUIToContextAndOptions()
        if not contextFilename == "":
            self.options.contextFilename = contextFilename
        try:
            self.context.Save(self.options.contextFilename)
            self.frame.SetTitle("CSnake GUI - %s" % self.options.contextFilename)
        except:
            self.Error("Sorry, CSnakeGUI could not save the context to %s\n. Please check if another program is locking this file.\n" % self.options.contextFilename)
            
        try:
            self.options.Save(self.optionsFilename)
        except:
            self.Error("Sorry, CSnakeGUI could not save the options to %s\n. Please check if another program is locking this file.\n" % self.optionsFilename)
    
    def OnCreateCMakeFilesAndRunCMake(self, event):
        self.action = self.ActionCreateCMakeFilesAndRunCMake
        self.DoAction()
        
    def OnDetectRootFolders(self, event):
        additionalRootFolders = self.handler.FindAdditionalRootFolders()
        self.context.rootFolders.extend(additionalRootFolders)
        self.UpdateGUIAndSaveContextAndOptions()
    
    def FindAdditionalRootFolders(self, onlyForNewInstance=False):
        if onlyForNewInstance and self.context.IsCSnakeFileInRecentlyUsed():
            return
        
        additionalRootFolders = self.handler.FindAdditionalRootFolders()
        if len(additionalRootFolders):
            message =  "CSnakeGUI found additional root folders which are likely to be necessary for target %s.\n" % self.context.instance
            message += "Should CSnakeGUI add the following root folders?\n\n"
            for folder in additionalRootFolders:
                message += folder + "\n"
            message += "\n\nThis question will not appear again for this target, but you can later add the above root folders\nusing the Detect button\n"
                
            dlg = wx.MessageDialog(self.frame, message, 'Question', style = wx.YES_NO | wx.ICON_QUESTION)
            if dlg.ShowModal() == wx.ID_YES:
                self.context.rootFolders.extend(additionalRootFolders)
                self.UpdateGUIAndSaveContextAndOptions()
            
    def ActionCreateCMakeFilesAndRunCMake(self):
        self.FindAdditionalRootFolders(True)
        if self.handler.ConfigureProjectToBuildFolder(_alsoRunCMake = True, _callback = self):
            xrc.XRCCTRL(self.panelContext, "btnLaunchIDE").SetFocus()
            xrc.XRCCTRL(self.panelContext, "btnCreateCMakeFilesAndRunCMake").Disable()
            if self.context.instance.lower() == "gimias":
                self.ProposeToDeletePluginDlls(self.handler.GetListOfSpuriousPluginDlls(_reuseInstance = True))
        
    def OnConfigureALL(self, event):
        self.action = self.ActionConfigureThirdPartyFolder
        self.DoAction()
        if sys.platform == 'win32':
            for solutionPath in self.handler.GetThirdPartySolutionPaths():
                self.handler.Build(solutionPath)

        self.action = self.ActionCreateCMakeFilesAndRunCMake
        self.DoAction()
        if sys.platform == 'win32':
            self.handler.Build( self.handler.GetTargetSolutionPath() )

        self.action = self.ActionInstallFilesToBuildFolder
        self.DoAction()

    def ActionOnlyCreateCMakeFiles(self):
        self.FindAdditionalRootFolders(True)
        if self.handler.ConfigureProjectToBuildFolder(_alsoRunCMake = False):
            if self.context.instance.lower() == "gimias":
                self.ProposeToDeletePluginDlls(self.handler.GetListOfSpuriousPluginDlls(_reuseInstance = True))
        
    def OnConfigureThirdPartyFolder(self, event):
        self.action = self.ActionConfigureThirdPartyFolder
        self.DoAction()
        
    def ActionConfigureThirdPartyFolder(self):
        try:
            if self.handler.ConfigureThirdPartyFolders():
                xrc.XRCCTRL(self.panelContext, "btnInstallFilesToBuildFolder").SetFocus()
                xrc.XRCCTRL(self.panelContext, "btnConfigureThirdPartyFolder").Disable()

                if self.options.askToLaunchIDE:
                    self.AskToLaunchIDE(self.handler.GetThirdPartySolutionPaths()[0])
                
        except Exception, message:
            dlg = wx.MessageDialog(self.frame, "%s" % message, 'Error', style = wx.OK | wx.ICON_ERROR)
            dlg.ShowModal()
        
    def OnInstallFilesToBuildFolder(self, event):
        self.action = self.ActionInstallFilesToBuildFolder
        self.DoAction()

        
    def ActionInstallFilesToBuildFolder(self):
        self.FindAdditionalRootFolders(True)
        if not self.handler.InstallBinariesToBuildFolder():
            self.Error("Error while installing files.")
        else:
            xrc.XRCCTRL(self.panelContext, "btnCreateCMakeFilesAndRunCMake").SetFocus()
            xrc.XRCCTRL(self.panelContext, "btnInstallFilesToBuildFolder").Disable()

            
    def DoAction(self):
        self.SetStatus("Processing...")
        self.textLog.Clear()
        self.textLog.Refresh()
        self.textLog.Update()
        
        self.Report("--- Working, patience please... ---")
        self.SaveContextAndOptions()
        startTime = time.time()
        
        try:
            self.action()
        except AssertionError, e:
            self.Error(str(e))
            
        elapsedTime = time.time() - startTime
        self.Report("--- Done (%d seconds) ---" % elapsedTime)
        self.UpdateGUIAndSaveContextAndOptions()
        self.SetStatus("")
        
        #self.Restart()
        
    def Restart(self):
        """ Restart the application """
        arglist = []
        if( os.path.splitext(os.path.basename(sys.executable))[0].lower() == "python" ):
            arglist = [sys.executable]
            arglist.extend(sys.argv)
        os.execv(sys.executable, arglist)
                
    def OnSelectCSnakeFile(self, event): # wxGlade: CSnakeGUIFrame.<event_handler>
        """
        Select file containing the project that should be configured.
        """
        # Set path of that file that was selected before
        oldValue = self.context.csnakeFile
        if oldValue.find("/") == -1:
            oldPath = ""
        else:
            oldPathAndFilenameSplit = oldValue.rsplit("/", 1)
            oldPath = oldPathAndFilenameSplit[0] + "/"
            oldValue = oldPathAndFilenameSplit[1]

        dlg = wx.FileDialog(None, "Select CSnake file", wildcard = "Python source files (*.py)|*.py",defaultDir = oldPath, defaultFile = oldValue)
        
        if dlg.ShowModal() == wx.ID_OK:
            self.context.csnakeFile = dlg.GetPath()
            self.UpdateGUIAndSaveContextAndOptions()

    def SetBuildFolder(self, folder):
        self.context.buildFolder = folder
        
    def GetBuildFolder(self):
        return self.context.buildFolder
        
    def SetInstallFolder(self, folder):
        self.context.installFolder = folder

    def GetInstallFolder(self):
        return self.context.installFolder
        
    def SetKDevelopProjectFolder(self, folder):
        self.context.kdevelopProjectFolder = folder
        
    def GetKDevelopProjectFolder(self):
        return self.context.kdevelopProjectFolder
            
    def AddRootFolder(self, folder): # wxGlade: CSnakeGUIFrame.<event_handler>
        """
        Add folder where CSnake files must be searched to context.rootFolders.
        """
        try:
            self.context.AddRootFolder( folder )
            
            # Automatically find thirdparty folder
            defaultThirdPartyFolder = folder + "/../thirdParty/"
            defaultThirdPartyFolder = csnUtility.NormalizePath( defaultThirdPartyFolder )
            if not os.path.isdir( defaultThirdPartyFolder ):
                defaultThirdPartyFolder = folder + "/thirdparties/"
                defaultThirdPartyFolder = csnUtility.NormalizePath( defaultThirdPartyFolder )

            if os.path.isdir( defaultThirdPartyFolder ):
                message = "Found thirdparty folder: %s. Do you want to add it?" % defaultThirdPartyFolder
                dlg = wx.MessageDialog(self.frame, message, 'Question', style = wx.YES_NO | wx.ICON_QUESTION)
                if dlg.ShowModal() == wx.ID_YES:
                    self.AddThirdPartyFolder( defaultThirdPartyFolder )
        except Exception, message:
            mes = "%s" % message
            dlg = wx.MessageDialog(self.frame, mes, 'Error', style = wx.OK | wx.ICON_ERROR)
            dlg.ShowModal()
    
    
    def GetLastRootFolder(self):
        if len(self.context.rootFolders) > 0:
            return self.context.rootFolders[len(self.context.rootFolders)-1]
        else:
            return ""

    def OnRemoveRootFolder(self, event): # wxGlade: CSnakeGUIFrame.<event_handler>
        """
        Remove folder where CSnake files must be searched from context.rootFolders.
        """
        folder = self.lbRootFolders.GetStringSelection()
        if folder in self.context.rootFolders:
            self.context.rootFolders.remove(folder)
            self.UpdateGUIAndSaveContextAndOptions()

    def AddThirdPartyFolder(self, folder): # wxGlade: CSnakeGUIFrame.<event_handler>
        """
        Add folder where CSnake files must be searched to context.thirdPartyFolders.
        """
        defaultBuildThirdPartyFolder = self.context.buildFolder + "/thirdParty"
        message = "Do you want to use \"%s\" as Build Folder for Third Party folder \"%s\"?" % (defaultBuildThirdPartyFolder, folder)
        dlg = wx.MessageDialog(self.frame, message, 'Question', style = wx.YES_NO | wx.ICON_QUESTION)
        if dlg.ShowModal() == wx.ID_YES:
            self.context.AddThirdPartySrcAndBuildFolder(folder, defaultBuildThirdPartyFolder)
        else:
            self.context.AddThirdPartySrcAndBuildFolder(folder, "")

    def OnThirdPartySrcAndBuildFolderSelectCell(self, event):
        self.lbThirdPartySrcAndBuildFolders.SelectRow(event.GetRow())
        event.Skip()
    
    def ThirdPartySrcAndBuildFolderGetSelectedRows(self):
        selection = self.lbThirdPartySrcAndBuildFolders.GetSelectedRows()
        return selection

    def OnAddThirdPartySrcAndBuildFolder(self, event):
        self.context.AddThirdPartySrcAndBuildFolder("", "")
        self.UpdateGUIAndSaveContextAndOptions()
        self.lbThirdPartySrcAndBuildFolders.ClearSelection()
        newRow = self.lbThirdPartySrcAndBuildFolders.GetTable().GetNumberRows()-1
        self.lbThirdPartySrcAndBuildFolders.SelectRow(newRow, True)
        self.lbThirdPartySrcAndBuildFolders.SetGridCursor(newRow, 0)
        self.lbThirdPartySrcAndBuildFolders.SetFocus()

    def OnRemoveThirdPartySrcAndBuildFolder(self, event):
        selection = self.ThirdPartySrcAndBuildFolderGetSelectedRows()
        if (len(selection) == 0):
            message = "You have to select at least one row! You can click on the row index to select a row."
            wx.MessageDialog(self.frame, message, 'Warning', style = wx.OK | wx.ICON_EXCLAMATION).ShowModal()
        else:
            for i in range(len(selection)):
                self.context.RemoveThirdPartySrcAndBuildFolderByIndex(selection[i])
                for j in range(i+1, len(selection)):
                    if selection[j] > selection[i]:
                        selection[j] = selection[j] - 1
            self.UpdateGUIAndSaveContextAndOptions()
            self.lbThirdPartySrcAndBuildFolders.ClearSelection()
        self.lbThirdPartySrcAndBuildFolders.SetFocus()
        
    def OnConfigureThirdPartySrcAndBuildFolder(self, event):
        selection = sorted(self.ThirdPartySrcAndBuildFolderGetSelectedRows())
        if (len(selection) == 0):
            message = "You have to select at least one row! You can click on the row index to select a row."
            wx.MessageDialog(self.frame, message, 'Warning', style = wx.OK | wx.ICON_EXCLAMATION).ShowModal()
            self.lbThirdPartySrcAndBuildFolders.SetFocus()
        else:
            self.lbThirdPartySrcAndBuildFolders.SetFocus()
            for row in selection:
                source = self.context.GetThirdPartyFolder(row)
                build = self.context.GetThirdPartyBuildFolderByIndex(row)
                self.handler.ConfigureThirdPartyFolder( source, build, allBuildFolders = self.context.GetThirdPartyBuildFoldersComplete() )
        
    def OnMoveUpThirdPartySrcAndBuildFolder(self, event):
        selection = sorted(self.ThirdPartySrcAndBuildFolderGetSelectedRows())
        if (len(selection) == 0):
            message = "You have to select at least one row! You can click on the row index to select a row."
            wx.MessageDialog(self.frame, message, 'Warning', style = wx.OK | wx.ICON_EXCLAMATION).ShowModal()
        else:
            newSelection = []
            boundaryIndex = 0
            for index in selection:
                if index > boundaryIndex:
                    self.context.MoveUpThirdPartySrcAndBuildFolder(index)
                    newSelection.append(index-1)
                else:
                    boundaryIndex = index + 1
                    newSelection.append(index)
            self.UpdateGUIAndSaveContextAndOptions()
            self.lbThirdPartySrcAndBuildFolders.ClearSelection()
            first = True
            for row in newSelection:
                self.lbThirdPartySrcAndBuildFolders.SelectRow(row, True)
                if first:
                    self.lbThirdPartySrcAndBuildFolders.SetGridCursor(row, 0)
                    first = False
        self.lbThirdPartySrcAndBuildFolders.SetFocus()
        
    def OnMoveDownThirdPartySrcAndBuildFolder(self, event):
        selection = sorted(self.ThirdPartySrcAndBuildFolderGetSelectedRows(), reverse = True)
        if (len(selection) == 0):
            message = "You have to select at least one row! You can click on the row index to select a row."
            wx.MessageDialog(self.frame, message, 'Warning', style = wx.OK | wx.ICON_EXCLAMATION).ShowModal()
        else:
            newSelection = []
            boundaryIndex = self.context.GetNumberOfThirdPartyFolders() - 1
            for index in selection:
                if index < boundaryIndex:
                    self.context.MoveDownThirdPartySrcAndBuildFolder(index)
                    newSelection.append(index+1)
                else:
                    boundaryIndex = index - 1
                    newSelection.append(index)
            self.UpdateGUIAndSaveContextAndOptions()
            self.lbThirdPartySrcAndBuildFolders.ClearSelection()
            first = True
            for row in newSelection:
                self.lbThirdPartySrcAndBuildFolders.SelectRow(row, True)
                if first:
                    self.lbThirdPartySrcAndBuildFolders.SetGridCursor(row, 0)
                    first = False
        self.lbThirdPartySrcAndBuildFolders.SetFocus()
        
    def OnContextOpen(self, event): # wxGlade: CSnakeGUIFrame.<event_handler>
        """
        Let the user load a context.
        """
        dlg = wx.FileDialog(None, "Select CSnake context file", defaultDir = os.path.dirname(self.options.contextFilename), wildcard = "Context Files (*.CSnakeGUI;*.csnakecontext)|*.CSnakeGUI;*.csnakecontext|All Files (*.*)|*.*")
        if dlg.ShowModal() == wx.ID_OK:
            self.UpdateGUIAndSaveContextAndOptions()
            if self.LoadContext(dlg.GetPath()):
                self.BackupContextFile()

    def OnContextCreateACopy(self, event): # wxGlade: CSnakeGUIFrame.<event_handler>
        """
        Let the user save the context.
        """
        dlg = wx.FileDialog(None, "Copy CSnake context to...", defaultDir = os.path.dirname(self.options.contextFilename), wildcard = "*.CSnakeGUI", style = wx.FD_SAVE)
        if dlg.ShowModal() == wx.ID_OK:
            (root, ext) = os.path.splitext(dlg.GetPath())
            if ext == ".CSnakeGUI":
                contextFilename = dlg.GetPath()
            else:
                contextFilename = "%s.CSnakeGUI" % root
            contextFilename = dlg.GetPath()
            self.SaveContextAndOptions(contextFilename)

    def GetCompilerComboBoxItems(self):
        result = []
        result.append("Visual Studio 7 .NET 2003")
        result.append("Visual Studio 8 2005")
        result.append("Visual Studio 8 2005 Win64")
        result.append("Visual Studio 9 2008")
        result.append("Visual Studio 9 2008 Win64")
        result.append("KDevelop3")
        result.append("Unix Makefiles")
        result.append("Eclipse CDT4 - Unix Makefiles")
        return result
        
    def GetBuildTypeComboBoxItems(self):
        #print self.context.compiler.GetAllowedConfigurations()
        return self.context.compiler.GetAllowedConfigurations()
    
    def GetCSnakeFileComboBoxItems(self):
        result = list()
        count = 0
        for x in self.context.recentlyUsed:
            result.append("%s - In %s" % (x.instance, x.csnakeFile))
            count += 1
            if count >= 10:
                break
        return result
    
    def UpdateGUIAndSaveContextAndOptions(self):
        """ Refreshes the GUI based on the current context. Also saves the current context to the contextFilename """
        self.binder.UpdateControls()
        self.panelKDevelop.Show( self.context.compiler.GetName() in ("KDevelop3") )
        self.SaveContextAndOptions()
        self.frame.Layout()
        self.frame.Refresh()
        self.frame.Update()
        wx.CallAfter(self.frame.Update)
    
    def LoadContext(self, contextFilename = ""):
        """
        Load configuration context from contextFilename.
        """
            
        if contextFilename == "":
            contextFilename = self.options.contextFilename
        else:
            self.options.contextFilename = contextFilename
            
        if not os.path.exists(self.options.contextFilename):
            self.Error("CSnakeGUI could not find context file %s" % self.options.contextFilename)
            return False
        
        #try:
        if not self.converter.Convert(self.options.contextFilename):
            self.Error("CSnakeGUI tried to open %s, but this file is not a valid context file" % self.options.contextFilename)
            return False
        self.SetContext(self.handler.LoadContext(contextFilename))
        self.frame.SetTitle("CSnake GUI - %s" % self.options.contextFilename)
        self.UpdateGUIAndSaveContextAndOptions()
        #except:
        #    self.Error("CSnakeGUI tried to open %s, but this file is not a valid context file" % self.options.contextFilename)
        #    return False

        return True

    def SetContext(self, context):
        self.context = context
        self.binder.SetBuddyClass("context", self.context)
        
    def OnUpdateListOfTargets(self, event): # wxGlade: CSnakeGUIFrame.<event_handler>
        self.SetStatus("Retrieving list of targets")
        self.listOfPossibleTargets = self.handler.GetListOfPossibleTargets()
        if len(self.listOfPossibleTargets):
            self.context.instance = self.listOfPossibleTargets[0]
        self.UpdateGUIAndSaveContextAndOptions()
        self.SetStatus("")
        xrc.XRCCTRL(self.panelContext, "btnCreateCMakeFilesAndRunCMake").Enable()
        xrc.XRCCTRL(self.panelContext, "btnInstallFilesToBuildFolder").Enable()  
        xrc.XRCCTRL(self.panelContext, "btnConfigureThirdPartyFolder").Enable()


    def GetInstanceComboBoxItems(self):
        return self.listOfPossibleTargets
            
    def ProposeToDeletePluginDlls(self, spuriousDlls):
        if len(spuriousDlls) == 0:
            return
            
        dllMessage = ""
        for x in spuriousDlls:
            dllMessage += ("%s\n" % x)
            
        message = "In the build results folder, CSnake found GIMIAS plugins that have not been configured.\nThe following plugin dlls may crash GIMIAS:\n\n%s\nDelete them?" % dllMessage
        dlg = wx.MessageDialog(self.frame, message, 'Question', style = wx.YES_NO | wx.ICON_QUESTION)
        if dlg.ShowModal() != wx.ID_YES:
            return
            
        for dll in spuriousDlls:
            os.remove(dll)

    def AskToLaunchIDE(self, pathToSolution):
        message = "Launch Visual Studio with solution %s?" % pathToSolution
        dlg = wx.MessageDialog(self.frame, message, 'Question', style = wx.YES_NO | wx.ICON_QUESTION)
        if dlg.ShowModal() == wx.ID_YES:
            argList = [self.context.idePath, pathToSolution]
            subprocess.Popen(argList)

    def OnLaunchIDE(self, event = None):
        argList = [self.context.idePath, self.handler.GetTargetSolutionPath()]
        subprocess.Popen(argList)
    
    def OnExit(self, event = None):
        if not self.destroyed:
            self.destroyed = True
            self.CopyGUIToContextAndOptions()
            if os.path.exists(self.options.contextFilename):
                self.SaveContextAndOptions(self.options.contextFilename)
            self.frame.Destroy()

    def OnHelp(self, event = None):
        ''' Text displayed for help.'''
        indexFilename = csnUtility.GetRootOfCSnake() + "/doc/html/index.html"
        if os.path.exists(indexFilename):
            webbrowser.open(indexFilename)
        else:
            dialog = wx.MessageDialog(self.frame, "Missing documentation.", 'Error', style = wx.OK | wx.ICON_ERROR)
            dialog.ShowModal()
                                        
    def OnAbout(self, event = None):
        ''' Text displayed in the About box.'''
        about = About()
        about.read(csnUtility.GetRootOfCSnake() + "/resources/about.txt")
        wx.AboutBox(about.getWxAboutDialogInfo())
        
    def OnSelectRecentlyUsed(self, event): # wxGlade: CSnakeGUIFrame.<event_handler>
        item = self.context.csnakeFile.GetSelection()
        context = self.context.recentlyUsed[item]
        self.context.csnakeFile = context.csnakeFile
        self.context.instance = context.instance
        self.UpdateGUIAndSaveContextAndOptions()

    def OnContextAbandonChanges(self, event): # wxGlade: CSnakeGUIFrame.<event_handler>
        try:
            shutil.copy(self.contextBeforeEditingFilename, self.options.contextFilename)
            self.LoadContext()
        except:
            self.Warn("Sorry, could not copy %s to %s. You can try copying the file manually" % (self.contextBeforeEditingFilename, self.options.contextFilename))

    def OnSetCMakePath(self, event): # wxGlade: CSnakeOptionsFrame.<event_handler>
        """
        Let the user select where CSnake is located.
        """
        dlg = wx.FileDialog(None, "Select path to CMake")
        if dlg.ShowModal() == wx.ID_OK:
            self.context.cmakePath = dlg.GetPath()
            self.UpdateGUIAndSaveContextAndOptions()

    def OnSetPythonPath(self, event): # wxGlade: CSnakeOptionsFrame.<event_handler>
        dlg = wx.FileDialog(None, "Select path to Python")
        if dlg.ShowModal() == wx.ID_OK:
            self.context.pythonPath = dlg.GetPath()
            self.UpdateGUIAndSaveContextAndOptions()

    def OnSetVisualStudioPath(self, event): # wxGlade: CSnakeOptionsFrame.<event_handler>
        dlg = wx.FileDialog(None, "Select path to Visual Studio")
        if dlg.ShowModal() == wx.ID_OK:
            self.context.idePath = dlg.GetPath()
            self.UpdateGUIAndSaveContextAndOptions()

    def SelectProjects(self, forceRefresh = False):
        # get list of ALL the categories on which the user can filter
        self.SetStatus("Retrieving projects...")
        previousFilter = self.context.filter 
        self.context.filter = list()
        try:
            categories = self.handler.GetCategories(forceRefresh)
        except:
            message = "Could not load project dependencies for instance %s from file %s." % (self.context.instance, self.context.csnakeFile)
            message = message + "\nPlease check the fields 'CSnake File' and 'Instance'"
            self.Error(message)
            return
            
        self.context.filter = previousFilter
        
        # create list of checkboxes for the categories
        self.panelSelectProjects.GetSizer().Clear()
        for category in self.projectCheckBoxes.keys():
            self.projectCheckBoxes[category].Destroy()
        self.projectCheckBoxes.clear()
        
        for category in sorted(categories):
            self.projectCheckBoxes[category] = wx.CheckBox(self.panelSelectProjects, -1, category)
            self.projectCheckBoxes[category].SetValue( not category in self.context.filter )
            self.panelSelectProjects.GetSizer().Add(self.projectCheckBoxes[category], 0, 0, 3)
            self.panelSelectProjects.Bind(wx.EVT_CHECKBOX, self.OnCategoryCheckBoxChanged, self.projectCheckBoxes[category])

        # create list of checkboxes for the 'super categories' (which are groups of normal categories, such as Tests)
        for super in self.context.subCategoriesOf.keys():
            value = True
            for sub in self.context.subCategoriesOf[super]:
                value = value and (not sub in self.context.filter)
                    
            self.projectCheckBoxes[super] = wx.CheckBox(self.panelSelectProjects, -1, super)
            self.projectCheckBoxes[super].SetValue( value )
            self.panelSelectProjects.GetSizer().Insert(0, self.projectCheckBoxes[super], 0, 0, 3)
            self.panelSelectProjects.Bind(wx.EVT_CHECKBOX, self.OnSuperCategoryCheckBoxChanged, self.projectCheckBoxes[super])
            
        self.panelSelectProjects.GetSizer().Add(self.btnForceRefreshProjects, 0, 0, 3)
        self.panelSelectProjects.Layout()
        self.panelSelectProjects.FitInside()
        self.SetStatus("")
        
    def OnSuperCategoryCheckBoxChanged(self, event): # wxGlade: CSnakeOptionsFrame.<event_handler>
        """ 
        Respond to checking a supercategory (such as Tests or Demos). Results in (un)checking all subcategories in that
        supercategory.
        """
        for super in self.context.subCategoriesOf.keys():
            value = self.projectCheckBoxes[super].GetValue()
                    
            for cbName in self.projectCheckBoxes.keys():
                if cbName in self.context.subCategoriesOf[super]:
                    self.projectCheckBoxes[cbName].SetValue(value)
                    
        self.OnCategoryCheckBoxChanged(event)
        
    def OnCategoryCheckBoxChanged(self, event): # wxGlade: Dialog.<event_handler>
        """ 
        Updates the category filter, based on the current status of the checkbox for each category.
        """
        for category in self.projectCheckBoxes.keys():
            if category in self.context.filter:
                self.context.filter.remove(category)
            if not self.projectCheckBoxes[category].GetValue():
                self.context.filter.append(category)
                
    def OnSelectCompiler(self, event):
        #self.binder.UpdateControls()
        #self.SetContext(csnContext.FindCompiler(self.context.compiler))
        self.context.FindCompiler()
        self.UpdateGUIAndSaveContextAndOptions()

    def RefreshProjects(self, event):
        self.SelectProjects(forceRefresh=True)

    def GetLastThirdPartyFolder(self):
        return self.context.GetLastThirdPartyFolder( )
    
if __name__ == "__main__":
    # create user folder
    userFolder = os.path.expanduser("~") + "/.csnake"
    if not os.path.exists(userFolder):
        os.mkdir(userFolder)
    # log file name
    logfilename = userFolder + "/log.txt"
    # set an environment variable to retrieve it in the log configuration
    os.environ["CSNAKELOGFILE"] = logfilename
    # logging initialization (should create the log file)
    logging.config.fileConfig(csnUtility.GetRootOfCSnake() + "/resources/logging.conf")
    logger = logging.getLogger("CSnake")
    
    logger.info("Starting program.")

    app = CSnakeGUIApp(0)
    app.MainLoop()
    
    logger.info("Ending program.")
